const assert=require('node:assert/strict');
const fs=require('node:fs');

const board=fs.readFileSync('player-board.js','utf8');
const bench=fs.readFileSync('dps-bench.js','utf8');
const dungeon=fs.readFileSync('fixed-dungeon.js','utf8');
const connected=fs.readFileSync('connected-rooms.js','utf8');
const exploration=fs.readFileSync('exploration.js','utf8');
const profile=fs.readFileSync('profile-storage.js','utf8');
const html=fs.readFileSync('index.html','utf8');
const wide=fs.readFileSync('wide.html','utf8');
const abilityNames={};
for(const statement of board.match(/Object\.assign\(NAMES,\{[^\n]+\}\);/g)||[])new Function('NAMES',statement)(abilityNames);
const actionIconBody=board.match(/const ACTION_ICON_FILES=\{([\s\S]*?)\n\};/)?.[1]||'';
const actionIds=[...actionIconBody.matchAll(/(?:^|,)\s*([a-z][a-z0-9_]*)\s*:/g)].map(match=>match[1]).filter(id=>id!=='dagger');
const specialAbilityNames={sword:'Heroic Strike',critical:'Critico',frost_armor:'Ice Barrier',power_word_shield:'Power Word: Shield',shadow_word_pain:'Shadow Word: Pain',avengers_shield:"Avenger's Shield",paladin_holy_shield:'Holy Shield',divine_strike:'Colpo Divino',blessing_protection:'Blessing of Protection',blessing_sanctuary:'Blessing of Sanctuary',hammer_justice:'Hammer of Justice',curse_agony:'Curse of Agony',curse_exhaustion:'Curse of Exhaustion'};
for(const id of actionIds){const expected=specialAbilityNames[id]||id.split('_').map((word,index)=>index&&['of','on'].includes(word)?word:word[0].toUpperCase()+word.slice(1)).join(' ');assert.equal(abilityNames[id],expected,`Il database deve mostrare ${id} con il nome canonico ${expected}`)}
assert.equal(abilityNames.critical,'Critico','Anche Critico deve usare il nome canonico del database');
assert.match(board,/replaceAll\(alias,codeName\)/,'I vecchi alias devono essere convertiti verso il nome canonico, non viceversa');

assert.match(board,/warlockShadowPower\(h,3,card\)/,'Shadow Bolt deve partire da 3');
assert.match(board,/corruption'\)\{dealt=warlockDotHit/,'Corruption deve colpire subito');
assert.match(board,/piercing_shot'\)dealt=.*hunterMarked\?1:0/,'Piercing Shot deve ricevere +1 dal Braccato');
assert.match(board,/fang_command'\).*hunterMarked\?1\+/,'Fang Command deve ricevere +1 dal Braccato');
assert.doesNotMatch(board,/startRecoveryTurn\([^)]*\).*stripWounds/s,'Il Recupero non deve cancellare le Ferite');
assert.match(board,/warchief:.*special:.*longCast:true/,'La Cascata di Acido deve essere un Cast Lungo');
assert.match(board,/goblin:.*tactic:\{pattern:'around',damage:2,damageType:'poison',wounds:1/,'La Tactic del Razziatore deve introdurre danno Poison nel nemico più comune');
assert.match(board,/if\(e\.megaBombCasting&&\(e\.longCastReadyRound\|\|0\)<=g\.round\).*turn\.cards=\['special'\]/,'Il Cast Lungo deve completarsi dal turno successivo');
assert.match(board,/type:'engineerBomb'.*megaBombCasting:true.*longCast:'mega_bomb'/,'La bomba deve essere interrompibile');
assert.match(board,/g\.state==='playing'&&h\.consumableTurnUsed/,'I consumabili devono avere il limite per turno');
assert.match(bench,/const cardName=id=>GAME_DATA\.cardNames\[id\]/,'Il benchmark deve leggere i nomi delle abilità dal database del gioco');
assert.match(bench,/warlock:\[\['shadow_bolt',cardName\('shadow_bolt'\),3\]/,'Il benchmark deve usare Shadow Bolt da 3 tramite il database dei nomi');
assert.match(bench,/shadow_mastery'\)\*ticks/,'Il benchmark deve applicare Shadow Mastery a ogni tick dei DoT');
assert.match(board,/function overlordEnemyActivationIds\(g\)/,'Il benchmark deve poter variare il numero di attivazioni nemiche');
assert.match(board,/!repeatedOverlordAction\(g\)&&tickWarlockEnemyEffects/,'I DoT devono scattare una volta per turno nemico, non per azione');
assert.match(board,/runEnemyActionBenchmark/,'Deve esistere il confronto reale tra una e due azioni nemiche');
assert.match(board,/longCastReadyRound=g\.round\+1/,'Il Cast Lungo deve lasciare una finestra di interruzione anche con due azioni');
assert.match(board,/enemyUniqueActions&&repeatedOverlordAction/,'La variante deve impedire due Command uguali nello stesso turno nemico');
assert.match(board,/function enemyCommandPlayable\(g,e,action[^\n]+lastChoiceByEnemy/,'La seconda Command uguale deve risultare disabilitata anche nell’interfaccia');
assert.match(board,/Spedizione reale: stessa compagnia, HP, Ferite, Bag, equip, livelli, talenti e mazzo/,'Il benchmark deve concatenare l’intera spedizione');
assert.match(board,/classic_guard[\s\S]*classic_assault[\s\S]*wild_guard[\s\S]*wild_assault/,'Il benchmark deve coprire tutte le classi e i rami');
assert.match(board,/two_low.*2 Command diverse · 40% danno · 1 Ferita\/round.*enemyActions:2,enemyDamageMultiplier:\.4,enemyWoundCapPerRound:1/,'Il benchmark spedizione deve provare due Command al 40%');
assert.match(board,/two_lower.*2 Command diverse · 35% danno · 1 Ferita\/round.*enemyActions:2,enemyDamageMultiplier:\.35,enemyWoundCapPerRound:1/,'Il benchmark spedizione deve provare due Command al 35%');
assert.match(board,/game\.enemyDamageMultiplier=mode\.enemyDamageMultiplier\|\|1;game\.enemyWoundCapPerRound=mode\.enemyWoundCapPerRound;game\.enemyUniqueActions=mode\.uniqueEnemyActions/,'Il benchmark spedizione deve applicare danno e limite Ferite della variante');
assert.match(board,/cap-g\.enemyWoundsApplied/,'Le Tactic devono poter limitare le Ferite complessive del round');
assert.match(board,/const every=Math\.max\(1,Number\(g\.enemyBonusActivationEvery\)\|\|1\),bonus=\(g\.round\|\|1\)%every\?0:/,'Il motore deve conservare il supporto per la cadenza configurata');
assert.match(board,/hero\.deck\.filter\(card=>card==='wound'\)\.length/,'Il benchmark spedizione deve misurare le Ferite persistenti');
assert.match(board,/delete g\.aiRecoveryDoneRoles;finishRecoveryTurn\(g\)/,'L’AI deve poter terminare il Recupero e proseguire la spedizione');
assert.match(board,/composition\.offers\.find\(entry=>entry\.targetId===destination\)\|\|composition\.offers\.find\(entry=>!g\.temple\.visited\.includes\(entry\.targetId\)\)/,'L’AI deve scegliere una delle due stanze realmente offerte');
assert.match(board,/if\(g\.state!=='loot'\)g\.lootReturnState=g\.state/,'Una seconda ricompensa non deve intrappolare lo stato nel loot');
assert.match(board,/game\.benchmarkMode\|\|gameModalOpen\(\)/,'Il timer UI non deve interferire con il benchmark');
assert.match(board,/game\?\.benchmarkMode\|\|!gameSfxEnabled\(\)/,'L’audio non deve consumare casualità durante il benchmark');
assert.match(board,/game\.state==='loot'\)\{aiLootStep\(game\);acted=true\}/,'Il benchmark deve distribuire il loot senza attendere timer UI');
assert.match(board,/role==='hunter'[\s\S]*reachable\('hunter_bow'\)[\s\S]*useHunterBow/,'L’IA Hunter deve poter usare l’arco base');
assert.match(board,/card==='split_arrow'\)chosen=hunterMarkedEnemy\(g\)/,'L’IA deve usare Split Arrow soltanto sul bersaglio Braccato');
assert.match(board,/const base=\{fireball:4,fire_blast:2,scorch:2,pyroblast:6\}/,'Fireball deve distinguere Fire sul bersaglio singolo con 5 danni usando lo staff base');
assert.match(board,/const value=2\*\(h\.talents\?\.ignite\|\|0\)\+talentBoost\(h,'ignite','damage'\)/,'Ignite deve infliggere 2 danni ritardati per grado');
assert.match(board,/h\.combustionCharges--.*power\+=2\+talentBoost\(h,'combustion','damage'\)/,'Combustion deve potenziare di 2 i prossimi colpi Fire');
assert.match(board,/function warlockDotHit\([^\n]+if\(value&&enemy\.hp\)warlockImpProc\(g,h,enemy\)/,'L’Imp deve reagire anche ai danni periodici del Warlock');
assert.match(board,/h\.impDamage\|\|1\)\+\(h\.talents\?\.master_demonologist\?2:0\)/,'Master Demonologist deve aggiungere 2 danni ai colpi dell’Imp');
assert.match(board,/function dismissWarlockPet\([^\n]+h\.impCharges=0;h\.impDamage=1;for\(const hero of g\.party\)hero\.voidwalkerGuard=0/,'Imp e Voidwalker devono essere pet mutuamente esclusivi');
assert.match(board,/summon_imp'\)\{dismissWarlockPet\(g,h\)/,'Evocare l’Imp deve congedare il Voidwalker');
assert.match(board,/summon_voidwalker'\)\{dismissWarlockPet\(g,h\)/,'Evocare il Voidwalker deve congedare l’Imp');
assert.match(board,/card==='summon_voidwalker'\)chosen=h\.impCharges\?null:/,'L’IA non deve congedare un Imp che ha ancora cariche');
assert.match(board,/card==='summon_imp'\)chosen=h\.impCharges\|\|allies\.some\(ally=>ally\.voidwalkerGuard\)\?null:/,'L’IA non deve congedare un Voidwalker che sta ancora proteggendo');
assert.match(board,/!taker\|\|!assignLoot\(g,loot\.uid,taker\.role\)\)leaveLoot/,'L’AI deve scartare un loot che non riesce ad assegnare');
assert.match(board,/id:'hardcore'.*hpScale:2,damageScale:2,fungi:\{tick:2,boom:8\}/,'Hardcore deve mantenere HP doppi e danni ricalibrati');
assert.match(board,/game\.enemyActionsPerTurn=2;game\.enemyBonusActivationsPerTurn=0;game\.enemyBonusActivationEvery=1;game\.enemyUniqueActions=true;game\.enemyDamageMultiplier=\.35;game\.enemyWoundCapPerRound=1/,'La campagna deve usare due Command diverse con danno e Ferite ricalibrati');
assert.match(board,/game\.tutorial=true;game\.xpHalved=false;game\.enemyActionsPerTurn=1;game\.enemyBonusActivationsPerTurn=0;game\.enemyUniqueActions=false;game\.enemyDamageMultiplier=1;delete game\.enemyWoundCapPerRound/,'Il tutorial deve restare a una Command con danno pieno');
const blockHelpers=['warriorShieldBlock','paladinShieldBlock','heroShieldBlock','heroRoundBlock'].map(name=>board.match(new RegExp(`function ${name}\\([^\\n]+`))?.[0]).join('\n');
const {heroRoundBlock}=new Function(`${blockHelpers};return{heroRoundBlock}`)();
assert.equal(heroRoundBlock({role:'warrior',offhand:{block:2},talents:{shield_wall:3}}),4,'Il Block automatico 5 deve ridursi a 4');
assert.equal(heroRoundBlock({role:'paladin',offhand:{block:3},talents:{redoubt:2}}),4,'Il Block automatico del Paladino deve usare la stessa riduzione');
const preventHeroDamageSource=board.match(/function preventHeroDamage\(target,power,physical=false\)\{const frost=[^\n]+/)?.[0]||'';
const preventHeroDamage=new Function(`${preventHeroDamageSource};return preventHeroDamage`)();
const physicalBlock={shield:4},poisonBlock={shield:4};
assert.deepEqual(preventHeroDamage(physicalBlock,3,true).hit,0,'Il Block deve assorbire il danno fisico');
assert.equal(physicalBlock.shield,1,'Il danno fisico deve consumare il Block punto per punto');
assert.equal(preventHeroDamage(poisonBlock,3,false).hit,3,'Il danno non fisico deve ignorare il Block');
assert.equal(poisonBlock.shield,4,'Il danno non fisico non deve consumare il Block');
assert.match(board,/h\.shield=heroRoundBlock\(h\)/,'Il Block ridotto deve ricaricarsi automaticamente a inizio round');
assert.doesNotMatch(preventHeroDamageSource,/heroShieldBlock/,'Lo scudo non deve più ridurre passivamente ogni singolo colpo');
assert.match(exploration,/h\.shield=typeof heroRoundBlock==='function'\?heroRoundBlock\(h\):0/,'Anche le imboscate devono iniziare con il Block ricaricato');
assert.match(board,/gridStatus\(actor\.shield,'st-guard'[^\n]+Block fisico/,'Il Block residuo deve essere visibile sulla carta dell’eroe');
assert.doesNotMatch(board,/Block permanente/,'L’interfaccia non deve più descrivere il Block come permanente');
assert.match(dungeon,/id:'deep-gate'[\s\S]*terrainLayout:\{rows:5,cols:5/,'L’Ala Profonda deve iniziare su una griglia 5×5');
assert.match(dungeon,/id:'deep-gate'[\s\S]*name:'Le Porte di Radicava'[\s\S]*siege:true[\s\S]*wallHp:8,rounds:3[\s\S]*rewardWeapons:3/,'Radicava deve essere un assedio da tre ondate con cinque mura da 8 HP e tre ricompense Normal');
assert.match(dungeon,/id:'deep-cistern'[\s\S]*name:'Il Ponte delle Cisterne'[\s\S]*wallHp:8,rounds:4[\s\S]*rewardTier:'GOLD'[\s\S]*terrainLayout:\{rows:5,cols:5/,'Il secondo fronte deve essere un assedio Heroic 5×5 da quattro ondate');
assert.match(dungeon,/id:'deep-roots'[\s\S]*name:'Il Bastione delle Radici'[\s\S]*wallHp:8,rounds:5[\s\S]*damagePerEnemy:3[\s\S]*rewardTier:'GOLD2'[\s\S]*terrainLayout:\{rows:5,cols:5/,'Il terzo fronte deve essere un assedio Hardcore 5×5 da cinque ondate');
assert.doesNotMatch(dungeon,/id:'deep-defense'|id:'deep-heart'/,'Il vertical slice non deve conservare le vecchie stanze scollegate');
assert.match(connected,/fixedCampaignEntranceId\(g\.campaignWing\)/,'L’ingresso deve dipendere dallo scenario di assedio selezionato');
assert.match(board,/freshGame\.campaignWing=meta\?\.wing\|\|'temple'/,'La campagna deve conservare l’ala scelta');
assert.match(board,/Math\.max\(5,Math\.min\(10,\+g\?\.combatGridCols\|\|6\)\)/,'La griglia reale deve accettare cinque colonne');
assert.match(board,/if\(target\.boss\)forceTempleBossTile/,'Qualsiasi finale dichiarato deve materializzare il boss');
assert.match(board,/if\(isSiegeWing\(g\.campaignWing\)\)j\.deepWingCleared=true/,'La vittoria nell’assedio non deve alterare lo sblocco delle difficoltà del Tempio');
assert.match(board,/function revealSiegeWeaponLoot\(g,count=3,tier='SILVER',label='NORMAL',diff='normale'\)[^\n]+slot==='armor'[^\n]+weaponCount=armor\?Math\.max\(0,count-1\):count[^\n]+if\(armor\)ids\.push\(armor\)/,'L’assedio deve garantire un’armatura e usare gli altri due slot per le armi');
const siegeLootSource=board.match(/function revealSiegeWeaponLoot\([^\n]+/)?.[0],siegeItems={sword:{kind:'equipment',slot:'weapon',role:'warrior'},staff:{kind:'equipment',slot:'staff',role:'healer'},plate:{kind:'equipment',slot:'armor',role:'warrior'},cloth:{kind:'equipment',slot:'armor',role:'healer'}},revealSiegeLoot=new Function('SILVER_LOOT_POOL','GOLD_LOOT_BY_ROLE','GOLD2_LOOT_BY_ROLE','TREASURE_ITEMS','shuffle','lootEligibleHeroes','boardAudit','note',`${siegeLootSource};return revealSiegeWeaponLoot`)(Object.keys(siegeItems),{}, {},siegeItems,list=>[...list],(game,item)=>game.party.filter(hero=>item.role===hero.role),()=>{},()=>{}),siegeLootGame={party:[{role:'warrior'},{role:'healer'}],encounter:1};
revealSiegeLoot(siegeLootGame);assert.equal(siegeLootGame.pendingLoot.length,3);assert.equal(siegeLootGame.pendingLoot.filter(entry=>siegeItems[entry.item].slot==='armor').length,1);assert.equal(siegeLootGame.pendingLoot.filter(entry=>siegeItems[entry.item].slot!=='armor').length,2,'La ricompensa reale dell’Assedio deve essere composta da due armi e un’armatura');
assert.match(board,/const ARMOR_ROLES=\{warrior:\{type:'plate'[\s\S]*paladin:\{type:'plate'[\s\S]*rogue:\{type:'leather'[\s\S]*shaman:\{type:'leather'[\s\S]*hunter:\{type:'leather'[\s\S]*mage:\{type:'cloth'[\s\S]*healer:\{type:'cloth'[\s\S]*warlock:\{type:'cloth'/,'Le otto classi devono usare Plate, Leather o Cloth secondo il proprio ruolo');
assert.match(board,/const ARMOR_LEVELS=\[\{prefix:'silver',tier:'SILVER',level:'normal',hpBonus:1\},\{prefix:'gold',tier:'GOLD',level:'heroic',hpBonus:2\},\{prefix:'mythic',tier:'GOLD2',level:'hardcore',hpBonus:3\}\]/,'Ogni armatura deve avere i livelli Normal, Heroic e Hardcore');
assert.match(board,/slot:'armor',armorType:armor\.type,armorLevel:level\.level,hpBonus:level\.hpBonus/,'Ogni armatura generata deve essere equipaggiabile e conservare tipo, livello e bonus');
assert.match(board,/const SIEGE_LEVELS=\[[\s\S]*id:'profonda'[\s\S]*id:'profonda-heroic'[\s\S]*id:'profonda-hardcore'/,'Devono esistere gli assedi Normal, Heroic e Hardcore');
assert.match(board,/function deepWingButtonHtml\(\)[^\n]+required=RAID_LEVELS\[index\],locked=!cleared\[required\.id\][^\n]+Completa \$\{required\.label\}/,'Ogni assedio deve richiedere il completamento della stessa difficoltà del Tempio');
assert.match(board,/siegeUnlock=SIEGE_LEVELS\[idx\]\?\.label[\s\S]*Sbloccati[\s\S]*siegeUnlock/,'Il riepilogo del Tempio deve comunicare lo sblocco dell’assedio corrispondente');
const siegeButtonsSource=board.match(/function deepWingButtonHtml\(\)[^\n]+/)?.[0],siegeFixtures=[{id:'profonda',wing:'deep',label:'Assedio · Normal',sub:'',expectedLevel:9,expectedBuild:''},{id:'profonda-heroic',wing:'deep-heroic',label:'Assedio · Heroic',sub:'',expectedLevel:12,expectedBuild:''},{id:'profonda-hardcore',wing:'deep-hardcore',label:'Assedio · Hardcore',sub:'',expectedLevel:13,expectedBuild:''}],raidFixtures=[{id:'normale',label:'Normale'},{id:'heroic',label:'Heroic'},{id:'hardcore',label:'Hardcore'}],siegeButton=(html,id)=>html.match(new RegExp(`<button[^>]+data-siege-level="${id}"[^>]*>`))?.[0]||'',renderSieges=cleared=>new Function('SIEGE_LEVELS','RAID_LEVELS','loadCleared',`${siegeButtonsSource};return deepWingButtonHtml`) (siegeFixtures,raidFixtures,()=>cleared)();
let siegeHtml=renderSieges({});assert.match(siegeButton(siegeHtml,'profonda'),/disabled/);assert.match(siegeButton(siegeHtml,'profonda-heroic'),/disabled/);assert.match(siegeButton(siegeHtml,'profonda-hardcore'),/disabled/);
siegeHtml=renderSieges({normale:true});assert.doesNotMatch(siegeButton(siegeHtml,'profonda'),/disabled/);assert.match(siegeButton(siegeHtml,'profonda-heroic'),/disabled/);assert.match(siegeButton(siegeHtml,'profonda-hardcore'),/disabled/);
siegeHtml=renderSieges({normale:true,heroic:true});assert.doesNotMatch(siegeButton(siegeHtml,'profonda-heroic'),/disabled/);assert.match(siegeButton(siegeHtml,'profonda-hardcore'),/disabled/);
siegeHtml=renderSieges({normale:true,heroic:true,hardcore:true});assert.doesNotMatch(siegeButton(siegeHtml,'profonda-hardcore'),/disabled/);
assert.match(board,/hardcoreFungi=\['hardcore','profonda-hardcore'\]\.includes\(g\.difficulty\)/,'I funghi dell’assedio Hardcore devono aggiungere Ferite persistenti');
assert.match(board,/function siegeEntryCards\(g,objective\)[\s\S]*objective\.waves\[objective\.wave\][\s\S]*siege-entry-card/,'La fascia d’ingresso deve anticipare posizione e tipo dei nemici della prossima ondata');
assert.match(board,/g\.siegeDeployment=\{selectedRole:order\[0\]\|\|null,placedRoles:\[\]\}[\s\S]*function siegeDeploymentCells\(g,role=[\s\S]*placed\.has\(hero\.role\)[\s\S]*function confirmSiegeDeployment\(g\)/,'Lo schieramento deve occupare soltanto le caselle degli Eroi già posizionati');
assert.match(board,/function bindSiegeDeployment\(shell,g\)[\s\S]*data-siege-deploy-confirm[\s\S]*if\(g\.siegeDeployment\)bindSiegeDeployment/,'La griglia deve permettere di posizionare gli eroi e confermare lo schieramento');
assert.match(board,/if\(g\.siegeDeployment\)shell\.querySelectorAll\('\.real-hero-slot button'\)[\s\S]*button\.disabled=true/,'Durante lo schieramento nessuna azione normale deve essere utilizzabile');
assert.match(board,/if\(g\.siegeDeployment\)return aliveAiHeroesOnly\(g\)\?\(\)=>autoDeploySiege\(g\):null/,'Una compagnia interamente AI non deve bloccarsi nello schieramento');
assert.match(board,/objective\?\.siege\?\(origin\.col-cell\.col\)\*1000-Math\.abs\(origin\.row-cell\.row\)\*20:0/,'Nell’assedio i nemici senza attacchi validi devono avanzare verso il Bastione restando nella propria corsia');
assert.match(board,/objective\.siege&&wave>1\)\{g\.siegeWaveAnnouncement=[\s\S]*function showSiegeWaveAnnounce\(g,onDone\)/,'Le ondate successive devono avere un annuncio compatto con la propria composizione');
assert.match(board,/objective\.siege&&wave>1\)\{[\s\S]*hero\.siegeRallyWave=wave[\s\S]*Rally · 1 movimento gratuito per Eroe/,'Dalla seconda ondata ogni Eroe vivo deve ricevere un movimento Rally gratuito');
assert.match(board,/rally\?'✥ Muovi · RALLY'[\s\S]*if\(rally\)hero\.siegeRallyWave=null/,'Il movimento Rally deve essere visibile e consumarsi senza spendere azioni');
assert.match(board,/function siegeEnemyThreat\(g,enemy\)[\s\S]*enemyMoveDestination\(g,enemy\)\?\.col<=objective\.breachCol/,'L’Assedio deve riconoscere i nemici già alla breccia o a un movimento di distanza');
assert.match(board,/siege-threat-badge[\s\S]*ALLA BRECCIA[\s\S]*1 AVANZATA[\s\S]*⚠ Breccia:/,'Le minacce immediate devono essere visibili sia sulle carte sia nel pannello obiettivo');
assert.match(board,/if\(g\.siegeWaveAnnouncement\)return null/,'L’AI deve attendere la fine dell’annuncio della nuova ondata');
assert.match(dungeon,/deep-gate[\s\S]*fortifyPower:2[\s\S]*deep-cistern[\s\S]*Funghi del Miasma[\s\S]*deep-roots[\s\S]*2 Ferite/,'I tre Assedi devono dichiarare regole di campo diverse');
assert.match(board,/room\.heroExitTreasure>0\|\|activeDefenseObjective\(g\)\?\.siege/,'I Funghi devono attivarsi anche negli Assedi senza tesori');
assert.match(board,/power=objective\.fortifyPower\|\|1[\s\S]*objective\.block\+=power/,'Le barricate di Radicava devono applicare il proprio valore di Fortifica');
assert.match(board,/function resolveSiegeWallPressure\(g,objective,attackers\)[\s\S]*objective\.walls\[index\]=Math\.max\(0,before-hit\)[\s\S]*wallBreachedRound\[index\]=g\.round/,'Ogni corsia deve danneggiare e sfondare il proprio segmento di muro');
assert.match(board,/wallBreachedRound\[index\].*<g\.round\)escaped\.push\(enemy\)[\s\S]*defeatCause='city_breached'/,'La sconfitta deve avvenire soltanto se un nemico attraversa una breccia dal turno successivo');
assert.match(board,/function siegeWallCards\(g,objective\)[\s\S]*BRECCIA[\s\S]*siege-breach-damage/,'I cinque segmenti devono mostrare HP, danno e breccia direttamente sulla griglia');
assert.match(html,/real-grid-cells\.siege-grid\{grid-template-columns:minmax\(42px,.5fr\) repeat\(var\(--grid-cols\),minmax\(92px,1fr\)\) minmax\(42px,.5fr\)/,'L’Assedio deve usare mezza colonna mura, cinque colonne di campo e mezza colonna ingressi');
assert.match(board,/gridStatus\(actor\.paladinProtection,'st-holy','pal-winged-guard'/,'Blessing of Protection deve apparire negli stati della carta e del target ingrandito');
assert.match(board,/objective\.siege\?objective\.wave>=objective\.rounds&&!aliveEnemies\(g\)\.length:g\.round>=objective\.rounds/,'L’Assedio deve terminare solo dopo l’ultima ondata e con la griglia ripulita');
assert.match(board,/function siegeWaveReady\(g,objective,enemyCount=aliveFighters\(g\)\.length\)[^\n]+enemyCount===0[^\n]+g\.round>=\(objective\.nextWaveRound\?\?g\.round\)&&enemyCount<6/,'Le ondate devono anticipare a campo vuoto e ritardare con almeno sei nemici');
const siegeWaveReadySource=board.match(/function siegeWaveReady\([^\n]+/)?.[0];
const siegeWaveReady=new Function(`${siegeWaveReadySource};return siegeWaveReady`)();
const waveObjective={wave:1,rounds:3,nextWaveRound:2};
assert.equal(siegeWaveReady({round:1},waveObjective,1),false,'L’ondata non deve arrivare prima della cadenza normale se restano nemici');
assert.equal(siegeWaveReady({round:1},waveObjective,0),true,'Il campo vuoto deve anticipare l’ondata');
assert.equal(siegeWaveReady({round:2},waveObjective,5),true,'Alla scadenza cinque nemici non devono ritardare l’ondata');
assert.equal(siegeWaveReady({round:2},waveObjective,6),false,'Alla scadenza sei nemici devono ritardare l’ondata');
assert.equal(siegeWaveReady({round:3},waveObjective,5),true,'Un’ondata ritardata deve entrare appena i nemici scendono sotto sei');
assert.equal(siegeWaveReady({round:3},{...waveObjective,wave:3},0),false,'Dopo l’ultima ondata non devono comparire altri nemici');
assert.match(dungeon,/deep-gate[\s\S]*obstacles:\[\{row:2,col:3\},\{row:4,col:3\}\][\s\S]*deep-cistern[\s\S]*obstacles:\[\{row:1,col:3\},\{row:5,col:3\}\][\s\S]*deep-roots[\s\S]*obstacles:\[\{row:2,col:3\},\{row:3,col:3\},\{row:4,col:3\}\]/,'I tre Assedi devono avere geometrie di corsia differenti');
assert.match(board,/function combatGridObstacleKeys\(g\)[\s\S]*combatGridObstacleKeys\(g\)[\s\S]*grid-obstacle/,'Le celle ostacolo devono essere condivise da movimento, spawn e rendering');
const enemyFormationCellsSource=board.match(/  function enemyFormationCells\(g,enemies\)\{[\s\S]*?\n  \}/)?.[0]||'';
const ensureCombatPositionsSource=board.match(/  function ensureCombatPositions\(g\)\{[\s\S]*?\n  \}/)?.[0]||'';
const formationRuntime=new Function('gridSize','combatGridObstacleKeys','aliveEnemies','ENEMY_DEFINITIONS',`${enemyFormationCellsSource};${ensureCombatPositionsSource};return{enemyFormationCells,ensureCombatPositions}`)(g=>({rows:g.combatGridRows,cols:g.combatGridCols}),g=>new Set((g.combatGridObstacles||[]).map(cell=>`${cell.row}:${cell.col}`)),g=>g.enemies.filter(enemy=>enemy.hp>0),{goblin:{role:'bruiser'},engineer:{role:'support'},warchief:{role:'commander'}});
const formationEnemies=Array.from({length:8},(_,index)=>({id:index+1,type:index%3===1?'engineer':index%3===2?'warchief':'goblin',hp:10})),formationGame={encounter:0,combatGridRows:5,combatGridCols:5,combatGridObstacles:[{row:2,col:3},{row:3,col:3},{row:4,col:3}],party:[{combatGridPos:{row:1,col:5}}],enemies:formationEnemies};
const formationCells=formationRuntime.enemyFormationCells(formationGame,formationEnemies),formationKeys=formationCells.map(cell=>`${cell.row}:${cell.col}`),formationBlocked=new Set(formationGame.combatGridObstacles.map(cell=>`${cell.row}:${cell.col}`));
assert.equal(formationCells.length,formationEnemies.length,'La formazione automatica deve trovare una casella per ogni nemico');
assert.equal(new Set(formationKeys).size,formationKeys.length,'La formazione automatica non deve sovrapporre i nemici');
assert.equal(formationKeys.some(key=>formationBlocked.has(key)),false,'La formazione automatica non deve mai collocare un nemico sopra una barricata');
const savedEnemy={id:21,type:'goblin',hp:10,combatGridPos:{row:3,col:3}},validEnemy={id:22,type:'engineer',hp:10,combatGridPos:{row:2,col:4}},savedGame={encounter:4,combatGridEncounter:4,combatGridRows:5,combatGridCols:5,combatGridObstacles:[{row:3,col:3}],party:[],enemies:[savedEnemy,validEnemy]};
formationRuntime.ensureCombatPositions(savedGame);
assert.notDeepEqual(savedEnemy.combatGridPos,{row:3,col:3},'Un salvataggio già bloccato deve spostare automaticamente il nemico fuori dalla barricata');
assert.notDeepEqual(savedEnemy.combatGridPos,validEnemy.combatGridPos,'Il recupero di un salvataggio bloccato non deve sovrapporre un altro nemico');
assert.match(board,/function patternAllowsTarget\(g,role,action,value\)[^\n]+gridLineOfEffectClear\(g,source,target\)[\s\S]*function enemyPatternAllowsTarget\(g,enemy,action,value\)[^\n]+gridLineOfEffectClear\(g,source,target\)/,'Le barricate devono bloccare simmetricamente le abilita dirette di Eroi e nemici');
assert.match(dungeon,/deep-gate[\s\S]*barricadeHp:6[\s\S]*deep-cistern[\s\S]*barricadeHp:6[\s\S]*deep-roots[\s\S]*barricadeHp:6/,'Tutti e tre gli Assedi devono iniziare con barricate da 6 HP');
assert.match(dungeon,/function applyFixedTempleLayout\(g,plan\)[\s\S]*hp:maxHp,maxHp/,'La preparazione della griglia deve assegnare vita e vita massima alle barricate');
assert.match(board,/function resolveEnemyBarricadeAttack\(g\)[^\n]+barricade\.hp=Math\.max\(0,barricade\.hp-damage\)[^\n]+g\.combatGridObstacles=g\.combatGridObstacles\.filter/,'I nemici devono danneggiare e distruggere una barricata adiacente');
assert.match(board,/if\(!moves\.length\)moves\.push\([^\n]+resolveEnemyBarricadeAttack\(sg\)[^\n]+resolveEnemyMovementActivation\(sg\)/,'L’IA deve preferire una barricata adiacente prima del movimento quando non può colpire Eroi');
assert.match(board,/data-overlord-barricade[\s\S]*querySelectorAll\('\[data-overlord-barricade\]'\)/,'L’Overlord umano deve poter ordinare l’attacco alla barricata');
assert.match(board,/barricade-hp[\s\S]*obstacle\.hp.*obstacle\.maxHp/,'La griglia deve mostrare gli HP rimasti sulle barricate');
const engineerBombCellsSource=board.match(/function engineerBombCells\(g,engineer\)\{[\s\S]*?\n  \}/)?.[0]||'';
assert.doesNotMatch(engineerBombCellsSource,/gridLineOfEffectClear/,'La Mega Bomba dell’Artificiere deve poter essere lanciata oltre una barricata');
const engineerBombCells=new Function(`const gridSize=()=>({rows:5,cols:5}),combatGridObstacleKeys=g=>new Set(g.combatGridObstacles.map(cell=>\`${'${cell.row}:${cell.col}'}\`)),aliveEnemies=g=>g.enemies,gridChests=()=>[],objectiveGridPosition=()=>null,actionPattern=()=>[[1,0],[2,0]];${engineerBombCellsSource};return engineerBombCells`)();
const bombGame={combatGridObstacles:[{row:2,col:3}],party:[],enemies:[{id:1,hp:10,combatGridPos:{row:2,col:2}}]};
assert.deepEqual(engineerBombCells(bombGame,bombGame.enemies[0]),[{row:2,col:4}],'La bomba deve poter atterrare dietro una barricata, ma non sopra di essa');
const barricadeHelpers=['combatGridBarricades','adjacentBarricade'].map(name=>board.match(new RegExp(`function ${name}\\([^\\n]+`))?.[0]).join('\n');
const {adjacentBarricade}=new Function(`${barricadeHelpers};return{adjacentBarricade}`)();
const barricadeGame={combatGridObstacles:[{row:2,col:3},{row:4,col:3,hp:2,maxHp:6}]};
assert.equal(adjacentBarricade(barricadeGame,{combatGridPos:{row:2,col:4}})?.row,2,'Una barricata ortogonalmente adiacente deve essere attaccabile');
assert.equal(adjacentBarricade(barricadeGame,{combatGridPos:{row:1,col:1}}),null,'Una barricata lontana non deve essere attaccabile');
assert.deepEqual(barricadeGame.combatGridObstacles[0],{row:2,col:3,hp:6,maxHp:6},'I vecchi salvataggi devono ricevere automaticamente 6 HP per barricata');
const resolveEnemyBarricadeAttackSource=board.match(/function resolveEnemyBarricadeAttack\([^\n]+/)?.[0]||'';
const resolveEnemyBarricadeAttack=new Function(`${barricadeHelpers};const enemyActionDamage=()=>3,boardAudit=()=>{},note=()=>{},enemyLabel=()=>'',prepareNextOverlordActivation=()=>{};${resolveEnemyBarricadeAttackSource};return resolveEnemyBarricadeAttack`)();
const attackGame={activeRole:'overlord',round:1,encounter:0,controllers:{overlord:'ai'},enemies:[{id:1,type:'goblin',combatGridPos:{row:2,col:4}}],combatGridObstacles:[{row:2,col:3,hp:6,maxHp:6}],commandDeck:{discard:[]},telemetry:{overlordCommand:{choiceLog:[]}},playerBoardAudit:{events:[]},overlordTurn:{enemyId:1,cards:['attack'],index:0}};
assert.equal(resolveEnemyBarricadeAttack(attackGame),true,'Il primo colpo alla barricata deve consumare l’attivazione');
assert.equal(attackGame.combatGridObstacles[0].hp,3,'Il primo colpo deve lasciare la barricata a 3 HP');
attackGame.overlordTurn={enemyId:1,cards:['attack'],index:1};
assert.equal(resolveEnemyBarricadeAttack(attackGame),true,'Il secondo colpo alla barricata deve consumare l’attivazione');
assert.equal(attackGame.combatGridObstacles.length,0,'Il secondo colpo da 3 deve distruggere la barricata da 6 HP');
assert.match(board,/function explodeDueEngineerBombs\(g\)[^\n]+damageEngineerBombTerrain\(g,bomb,power\)/,'L’esplosione della Mega Bomba deve applicare il danno anche al terreno');
const damageEngineerBombTerrainSource=board.match(/function damageEngineerBombTerrain\([^\n]+/)?.[0]||'';
const damageEngineerBombTerrain=new Function(`${barricadeHelpers};const activeDefenseObjective=g=>g.roomObjective,boardAudit=()=>{},note=()=>{};${damageEngineerBombTerrainSource};return damageEngineerBombTerrain`)();
const blastGame={round:2,combatGridObstacles:[{row:3,col:2,hp:6,maxHp:6},{row:2,col:2,hp:4,maxHp:6},{row:5,col:5,hp:6,maxHp:6}],roomObjective:{siege:true,walls:[8,8,8,8,8],wallBreachedRound:Array(5).fill(null),block:2,hp:40},playerBoardAudit:{events:[]}};
assert.deepEqual(damageEngineerBombTerrain(blastGame,{combatGridPos:{row:3,col:1}},5),{barricades:2,destroyed:1,wallDamage:3,blocked:2,wallsBroken:0},'Una bomba nella prima colonna deve colpire le barricate nell’area e un solo segmento di muro, consumando prima il Block');
assert.deepEqual(blastGame.roomObjective.walls,[8,8,5,8,8],'La bomba deve danneggiare soltanto il segmento di muro nella propria riga');
assert.equal(blastGame.roomObjective.hp,37,'Gli HP complessivi delle mura devono aggiornarsi dopo l’esplosione');
assert.deepEqual(blastGame.combatGridObstacles.map(cell=>[cell.row,cell.col,cell.hp]),[[3,2,1],[5,5,6]],'Le barricate distrutte devono sparire, quelle sopravvissute devono conservare gli HP rimasti');
const breachGame={round:4,combatGridObstacles:[],roomObjective:{siege:true,walls:[8,8,8,8,8],wallBreachedRound:Array(5).fill(null),block:0,hp:40},playerBoardAudit:{events:[]}};
assert.equal(damageEngineerBombTerrain(breachGame,{combatGridPos:{row:1,col:1}},10).wallsBroken,1,'Una bomba abbastanza potente deve poter aprire al massimo il segmento della propria riga');
assert.deepEqual(breachGame.roomObjective.wallBreachedRound.slice(0,2),[4,null],'La breccia creata dalla bomba deve ricordare il round senza propagarsi alle righe vicine');
assert.match(board,/id="menuStable">Scuderia/,'Il menu deve aprire la Scuderia');
assert.match(board,/function createStable\(menu\)/,'La Scuderia deve avere una vista dedicata');
assert.match(board,/HERO_CLASSES\.map\(hero=>stableHeroCard\(hero,heroes,selectedRoles\)\)/,'La Scuderia deve mostrare tutte le otto classi e la formazione salvata');
assert.match(board,/window\.RaidProfile\?\.load\(localStorage\)/,'La Scuderia deve leggere il profilo persistente');
assert.match(board,/build\?\.heroLevel[\s\S]*build\?\.xp[\s\S]*build\?\.deck[\s\S]*build\?\.collection/,'Le schede devono mostrare progressione e stato del mazzo reali');
assert.match(board,/specialization=developed\?stableSpecialization\(role,build\)[\s\S]*equipment=developed\?stableEscape\(stableEquipment\(build\)\)/,'Le schede devono mostrare specializzazione ed equipaggiamento reali');
assert.match(board,/account=loadAccount\(\),accountHeroes=account\?\.heroes\|\|\{\}/,'La formazione della compagnia deve leggere gli eroi dalla Scuderia');
assert.match(board,/roles\.map\(role=>accountHeroes\[role\]\)\.filter\(Boolean\);startLevel\(level,roles,roster/,'La nuova spedizione deve portare le build degli eroi selezionati');
assert.match(board,/account\?\.unlocks\?\.raidDifficultyIndex\|\|0/,'Le difficoltà sbloccate devono appartenere al profilo e non alla singola spedizione');
assert.match(board,/Livelli, talenti, mazzi ed equipaggiamenti resteranno nella Scuderia/,'Cambiare compagnia deve dichiarare che la progressione non viene cancellata');
assert.match(board,/function recoveredAccountBuild\(h\)[^\n]+build\.hp=build\.maxHp[^\n]+filter\(card=>card!=='wound'\)/,'Dopo una sconfitta la Scuderia deve conservare la build ma ripristinare vita e Ferite');
assert.match(board,/function persistAccountOnLoss\(g\)[^\n]+saveAccountHeroes\(roster,g\.companyName\|\|''\);recordAccountRun\('loss',g\);clearJourney\(\)/,'La sconfitta deve aggiornare la carriera, la Scuderia e chiudere la spedizione fallita');
assert.match(board,/game\.state==='lost'&&!game\.__accountLossSaved&&!game\.tutorial&&!game\.benchmarkMode&&!game\.combatGridScenario/,'Il salvataggio della sconfitta deve avvenire una sola volta e non contaminare tutorial o simulatori');
assert.match(board,/Progressi salvati nella Scuderia/,'La vittoria deve confermare il salvataggio nel riepilogo');
assert.match(board,/function stableDeckChange\(build,card,delta\)/,'La Scuderia deve consentire gli scambi del mazzo fuori dalla spedizione');
assert.match(board,/cleanSize>=DECK_CAP\|\|\(used\[card\]\|\|0\)>=DECK_COPY_MAX\|\|!\(available\[card\]>0\)/,'Gli scambi devono rispettare capienza, copie massime e carte possedute');
assert.match(board,/function stableJourneyStatus\(profile\)[^\n]+prossima spedizione da scegliere/,'La Scuderia deve spiegare che il percorso attivo non è una spedizione già selezionata');
assert.match(board,/RaidProfile\?\.write\(localStorage,profile\)/,'Le modifiche confermate devono essere salvate nel profilo senza toccare gli altri eroi');
assert.match(board,/function stableDepositItem\(build,stash,index\)/,'La Scuderia deve poter spostare oggetti dalla Bag al deposito comune');
assert.match(board,/function stableWithdrawItem\(build,stash,index\)/,'La Scuderia deve poter assegnare gli oggetti del deposito a un eroe compatibile');
assert.match(board,/function stableEquipFromBag\(build,stash,index,hand='left'\)/,'La Scuderia deve poter cambiare Equipment e conservare l’oggetto sostituito');
assert.match(board,/function stableDeleteInventory\(build,stash,source,index\)/,'La Scuderia deve poter eliminare oggetti dalla Bag e dal deposito');
assert.match(board,/function stableDeleteEquipped\(build,key\)/,'La Scuderia deve poter eliminare anche un oggetto equipaggiato');
assert.match(board,/data-stable-delete-item="\$\{source\}:\$\{index\}"[\s\S]*data-stable-delete-equipped/,'Ogni oggetto gestito nella Scuderia deve avere un comando di eliminazione');
assert.match(board,/Eliminare definitivamente \$\{name\}\?/,'L’eliminazione di un oggetto deve richiedere conferma');
assert.match(board,/\.stable-overlay img\.bag-item-icon\{filter:brightness\(0\) invert\(1\)!important\}/,'Le icone degli oggetti nella Scuderia devono essere bianche e leggibili');
assert.match(board,/const TALENT_TREES=\{[\s\S]*const TREES=TALENT_TREES/,'Scuderia e campagna devono condividere la stessa struttura degli alberi dei talenti');
assert.match(board,/\.talent-tree-node:hover,\.talent-tree-node:focus-within\{z-index:90\}/,'Il talento evidenziato deve portare il tooltip sopra le righe successive');
assert.match(board,/function stableStartRespec\(build\)[\s\S]*function stableInvestTalent\(build,id,budget\)/,'La Scuderia deve supportare un respec controllato con un budget di punti invariato');
assert.match(board,/respecBudget!==null&&stableTalentPoints\(draft\)!==respecBudget/,'Il respec non deve essere salvabile finché tutti i punti non sono stati redistribuiti');
assert.match(board,/class="deck-editor stable-deck-editor"[\s\S]*deck-card-grid deck-main-grid[\s\S]*deck-card-grid collection-grid/,'Il mazzo della Scuderia deve usare lo stesso linguaggio visivo dell’editor in gioco');
assert.doesNotMatch(board,/class="deck-editor stable-deck-editor"><header class="deck-editor-head"/,'Il pannello Mazzo non deve ripetere eroe e titolo già visibili nella Scuderia');
assert.match(board,/MAZZO IN GIOCO[\s\S]*<h3>\$\{deckSize\}\/\$\{DECK_CAP\} carte<\/h3>/,'Il conteggio del mazzo deve restare visibile nella testata utile');
assert.match(board,/\.stable-tab-panel \.deck-workspace\{grid-template-columns:repeat\(2,minmax\(0,1fr\)\);grid-template-rows:minmax\(0,1fr\)[^}]+\}[\s\S]*\.stable-tab-panel \.deck-zone-collection\{grid-column:2;grid-row:1\}/,'La Collezione della Scuderia deve restare visibile accanto al mazzo');
assert.match(board,/\.stable-tab-panel \.deck-main-grid\{grid-template-rows:repeat\(4,minmax\(0,1fr\)\)\}/,'Le quattro righe del mazzo devono adattarsi all’altezza disponibile');
assert.match(board,/class="stable-actions"><button[^>]+data-stable-save hidden>Salva modifiche<\/button><button[^>]+data-stable-back>/,'Salva modifiche e Scuderia devono condividere il footer fisso');
assert.doesNotMatch(board,/stable-save-row/,'Il salvataggio non deve occupare una seconda riga sotto il contenuto');
assert.match(board,/class="stable-header-equipment"[\s\S]*stableEquipmentItems\(currentRole,draft,false\)/,'L’Equipment deve restare sempre visibile accanto alla scheda dell’eroe');
assert.match(board,/stableEquipmentItems\(role,build,locked\)[\s\S]*armorItem=build\.armor[\s\S]*data-stable-delete-equipped="armor"/,'L’Equipment della Scuderia deve mostrare lo slot Armatura e l’armatura equipaggiata');
assert.match(board,/stable-header-equipment \.stable-equipment-cards\{[^}]*grid-template-columns:repeat\(3,minmax\(0,1fr\)\)/,'I tre slot Equipment devono stare sulla stessa riga');
assert.match(board,/class="stable-inventory-columns"><section class="stable-bag-pane"[\s\S]*Bag eroe[\s\S]*class="stable-storage"[\s\S]*Deposito compagnia/,'Bag eroe e deposito della compagnia devono essere due aree affiancate');
assert.doesNotMatch(board,/stable-inventory-section"><div class="stable-deck-head"><h3>Bag e deposito/,'Il pannello Bag non deve ripetere il titolo del tab');
assert.match(board,/savedDraft=JSON\.parse\(JSON\.stringify\(draft\)\);profile\.heroes\[currentRole\]=savedDraft;profile\.stash=JSON\.parse\(JSON\.stringify\(stashDraft\)\)/,'Bag, Equipment e deposito devono essere salvati insieme nel profilo');
assert.doesNotMatch(board,/if\(locked&&draft\)\{renderDraft\(profile\);return\}/,'Il percorso tra missioni non deve bloccare le modifiche all’inventario');
assert.match(board,/journeyHero=profile\.activeJourney\?\.roster\?\.findIndex[\s\S]*profile\.activeJourney\.roster\[journeyHero\]=JSON\.parse\(JSON\.stringify\(savedDraft\)\)/,'Le modifiche della Scuderia devono aggiornare anche la formazione del percorso attivo');
assert.match(board,/data-stable-roster=/,'La scheda eroe deve permettere di aggiungere o rimuovere l’eroe dalla formazione');
assert.match(board,/const rosterButton=\(profile,role\)=>\{if\(profile\?\.activeJourney\)return''/,'Durante un percorso attivo il comando formazione inutilizzabile non deve occupare spazio nella scheda eroe');
assert.match(board,/selected=new Set\(\(account\?\.selectedRoles\|\|\[\]\)\.filter/,'La nuova campagna deve proporre la formazione salvata');
assert.match(board,/profile\.selectedRoles=\[\.\.\.roles\];RaidProfile\.write\(localStorage,profile\)/,'Avviare una campagna deve salvare la formazione scelta');
assert.doesNotMatch(profile,/function clearProfileJourney\([^\n]+selectedRoles=\[\]/,'Terminare la spedizione non deve cancellare la formazione preferita');
assert.match(board,/function profileSummaryData\(profile\)/,'La home deve ricavare il riepilogo dal profilo persistente');
assert.match(board,/RaidProfile\?\.milestone\(profile\)[\s\S]*goal\.rank[\s\S]*goal\.label/,'La home deve mostrare il prossimo obiettivo della compagnia');
assert.match(board,/recordAccountRun\('win',g\)/,'Una vittoria deve aggiornare la carriera della compagnia');
assert.match(board,/stats\?\.heroes\?\.\[role\]/,'La Scuderia deve mostrare quante spedizioni ha giocato ogni eroe');
assert.match(board,/data-stable-hero-name[\s\S]*draft\.playerName=event\.target\.value\.trimStart\(\)\.slice\(0,24\)/,'La Scuderia deve permettere di rinominare un eroe sviluppato');
assert.match(board,/data-menu-profile[\s\S]*PROFILO COMPAGNIA/,'La home deve mostrare il riepilogo della compagnia');
assert.match(board,/data-stable-company-save[\s\S]*profile\.company=name;[\s\S]*RaidProfile\?\.write\(localStorage,profile\)/,'La Scuderia deve permettere di salvare il nome della compagnia');
assert.match(board,/new MutationObserver\(\(\)=>\{if\(!menu\.hidden\)syncProfile\(\)\}\)/,'Il riepilogo deve aggiornarsi quando si torna alla home');
assert.match(board,/\.hero-select-setup\{overflow:hidden/,'La selezione della spedizione non deve scorrere come una pagina HTML');
assert.match(board,/\.setup-combined-page\{grid-template-rows:[^}]+\}[\s\S]*\.hero-select-panel \.level-grid\{grid-template-columns:repeat\(3/,'Compagnia e sei spedizioni devono condividere una vista ordinata con griglia 3×2');
assert.match(board,/data-setup-combined[\s\S]*hero-pick-grid[\s\S]*setup-expedition-grid/,'Gli eroi leggibili devono precedere le spedizioni nella stessa schermata');
assert.doesNotMatch(board,/Scegli spedizione →|← Compagnia/,'I pulsanti di navigazione fra compagnia e spedizione non devono più esistere');
assert.match(board,/setup-expedition-grid\.locked[\s\S]*pointer-events:none[\s\S]*expeditionGrid\.classList\.toggle\('locked',!ready\)/,'Le spedizioni devono restare inattive finché non sono scelti quattro eroi');
assert.match(board,/hero-pick-copy[\s\S]*<small>\$\{specialization\}<\/small><strong>\$\{name\}<\/strong>/,'Ogni carta eroe deve mostrare specializzazione e nome');
assert.match(board,/\.main-menu\{overflow:hidden\}/,'Anche la home deve essere una schermata fissa senza scorrimento');
assert.match(html,/<meta name="viewport" content="width=1920,viewport-fit=cover">/,'Il gioco deve conservare il viewport Wide originale senza ricomporre carte e comandi');
assert.match(html,/portrait-lock[\s\S]*compagnia\.webp[\s\S]*Ruota il telefono[\s\S]*data-portrait-play>Gioca in verticale/,'Il portrait deve mostrare la Compagnia, l’invito a ruotare e l’alternativa giocabile');
assert.match(html,/portraitPlay=false[^\n]+play=phoneWide\.matches&&portrait&&portraitPlay[^\n]+wideWidth=1920[^\n]+rotate\(90deg\) scale\(\$\{scale\}\) translateY\(-100%\)/,'Il portrait deve ruotare la tela storica soltanto dopo la scelta del giocatore');
assert.match(html,/data-portrait-play[^\n]+portraitPlay=true;fitPhoneWide\(\)/,'Il pulsante deve permettere di giocare in verticale nella sessione corrente');
assert.match(html,/fitPhoneWide\(\);addEventListener\('resize',fitPhoneWide,\{passive:true\}\)/,'Girare il telefono deve aggiornare la stessa pagina senza ricaricarla');
assert.doesNotMatch(html,/wide\.html|location\.replace|iframe/,'Il gioco principale non deve più passare attraverso un iframe mobile');
assert.match(wide,/searchParams\.delete\('wide'\)[\s\S]*location\.replace\(gameUrl\)/,'I vecchi indirizzi Wide devono tornare una volta sola al gioco principale');
assert.doesNotMatch(wide,/<iframe|addEventListener\('resize'/,'Il vecchio contenitore non deve più renderizzare o ridimensionare il gioco');
assert.doesNotMatch(board,/\@media\(orientation:portrait\)/,'Selezione eroi e Scuderia devono conservare il layout Wide in verticale');
assert.match(board,/min-width:1101px\)[\s\S]*real-combat-shell\{grid-template-columns:minmax\(330px,390px\) minmax\(0,1fr\) minmax\(240px,320px\)/,'Il combattimento deve conservare le tre colonne della vecchia versione Wide');
assert.match(board,/orientation:landscape\)[\s\S]*max-height:1100px\)[\s\S]*real-combat-shell\{grid-template-columns:minmax\(430px,500px\) minmax\(0,1fr\) minmax\(180px,225px\)/,'Su telefono il combattimento deve conservare le proporzioni storiche tra abilità, griglia e target');
assert.match(board,/max-height:1100px\), \(hover:none\) and \(pointer:coarse\) and \(orientation:portrait\)\{body\.combat-grid-mode/,'Il portrait ruotato deve applicare le stesse regole storiche del Landscape');
assert.match(board,/real-combat-left \.hand\{flex:1 1 auto;grid-template-rows:repeat\(3,minmax\(84px,1fr\)\)/,'Le abilità devono restare ordinate in tre righe dentro il pannello storico');
assert.doesNotMatch(board,/max-width:1100px\) and \(max-height:600px\)[\s\S]*real-combat-shell/,'Il telefono non deve sostituire il layout storico con una variante compatta');
assert.match(board,/g\.gridTreasurePhase=true;g\.roomClearTurnPending=true;note\(g,'🎁 Combattimento concluso: completate i turni rimanenti/,'La fase tesoro deve conservare il turno e l’iniziativa correnti');
assert.doesNotMatch(board,/g\.gridTreasurePhase=true;movers\.forEach\(hero=>hero\.actions=CONFIG\.actionsPerRound\)/,'La morte dell’ultimo nemico non deve ricaricare le azioni di tutti gli Eroi');
assert.match(board,/tok==='overlord'\)\{if\(g\.roomClearTurnPending&&!aliveEnemies\(g\)\.length\)\{g\.initIndex\+\+;continue\}/,'L’Overlord senza nemici deve essere saltato durante i turni residui');
assert.match(board,/if\(g\.roomClearTurnPending&&!aliveEnemies\(g\)\.length&&!g\.exploration\?\.activeAmbush&&room\?\.treasureResolved\)\{g\.roomClearTurnPending=false;checkVictory\(g\);return\}/,'La stanza deve chiudersi soltanto alla fine del giro dopo aver risolto i tesori');
assert.match(board,/\.stable-overlay\{[^}]*overflow:hidden/,'La Scuderia deve restare dentro il viewport');
assert.match(board,/data-stable-tab="hero"[\s\S]*data-stable-tab="equipment"[\s\S]*data-stable-tab="deck"/,'La scheda eroe deve usare sezioni invece dello scorrimento');
assert.match(board,/function stableNewBuild\(role\)[\s\S]*?deck:\[\.\.\.deck\],collection:\[\.\.\.deck\][\s\S]*?return build/,'Un nuovo eroe deve avere subito una scheda base completa');
assert.match(board,/draft=saved\?JSON\.parse\(JSON\.stringify\(saved\)\):stableNewBuild\(role\)/,'La Scuderia deve aprire tutti i pannelli anche per un eroe nuovo');
assert.doesNotMatch(board,/if\(!draft\)\{content\.className='stable-new-view'/,'Un eroe nuovo non deve più fermarsi alla schermata vuota');
assert.match(board,/stable-inventory-columns \.bag-slots\{[^}]*overflow:auto/,'Bag eroe e deposito devono scorrere soltanto dentro le rispettive aree');
assert.match(board,/stable-inventory-columns \.hero-bag-slot\{[^}]*overflow:hidden/,'I comandi della Bag devono restare dentro la scheda dell oggetto');
assert.match(board,/stable-tab-panel \.deck-card-grid\{overflow:auto/,'Il mazzo deve restare consultabile nello stesso pannello');
assert.match(board,/data-stable-export>Esporta profilo[\s\S]*data-stable-import>Importa profilo/,'La Scuderia deve poter esportare e importare il profilo');
assert.match(board,/RaidProfile\?\.normalize\(parsed\?\.profile\|\|parsed\)[\s\S]*confirm\(`/,'Un backup deve essere validato e confermato prima di sostituire il profilo');

const lineOfEffectSource=['gridSegmentCrossesCell','gridLineOfEffectClear'].map(name=>board.match(new RegExp(`function ${name}\\([^\\n]+`))?.[0]).join('\n');
const{gridLineOfEffectClear}=new Function(`${lineOfEffectSource};return{gridLineOfEffectClear}`)();
assert.equal(gridLineOfEffectClear({combatGridObstacles:[{row:3,col:3}]},{row:3,col:1},{row:3,col:5}),false,'Una barricata attraversata deve bloccare la linea d’effetto');
assert.equal(gridLineOfEffectClear({combatGridObstacles:[{row:2,col:3}]},{row:1,col:1},{row:5,col:5}),true,'Sfiorare soltanto l’angolo di una barricata non deve bloccare');
assert.equal(gridLineOfEffectClear({combatGridObstacles:[{row:2,col:3}]},{row:1,col:1},{row:3,col:5}),false,'Una diagonale che attraversa l’interno della barricata deve essere bloccata');

const inventoryNames=['armorHpBonus','setHeroArmor','stableItemFitsRole','stableEnsureBag','stableStoreItem','stableDepositItem','stableWithdrawItem','stableBagCanTake','stableEquipFromBag','stableDeleteEquipped','stableDeleteInventory'];
const inventorySource=inventoryNames.map(name=>board.match(new RegExp(`function ${name}\\([^\\n]+`))?.[0]).join('\n');
const inventoryItems={potion:{kind:'consumable'},old_sword:{name:'Sword',kind:'equipment',role:'warrior',slot:'weapon'},great_axe:{name:'Greataxe',kind:'equipment',role:'warrior',slot:'weapon',twoHanded:true},shield:{name:'Shield',kind:'equipment',role:'warrior',slot:'offhand'},bow:{name:'Bow',kind:'equipment',role:'hunter',slot:'weapon'},warrior_armor:{name:'Warlord Plate',kind:'equipment',role:'warrior',slot:'armor',hpBonus:2},mage_armor:{name:'Runebound Robe',kind:'equipment',role:'mage',slot:'armor',hpBonus:2}};
const inventory=new Function('HERO_BAG_SLOTS','bagStackable','TREASURE_ITEMS','equipmentFromItem',`${inventorySource};return{stableDepositItem,stableWithdrawItem,stableEquipFromBag,stableDeleteEquipped,stableDeleteInventory}`)(9,id=>id==='potion',inventoryItems,(id,diff)=>({itemId:id,name:id,twoHanded:id==='great_axe',hpBonus:inventoryItems[id]?.hpBonus,acqDiff:diff||null}));
const inventoryBuild={role:'warrior',weapon:{itemId:'old_sword'},offhand:{itemId:'shield'},twoHanded:false,bag:[{item:'great_axe',count:1},{item:'potion',count:2}]},inventoryStash=[];
assert.equal(inventory.stableEquipFromBag(inventoryBuild,inventoryStash,0),true);assert.equal(inventoryBuild.weapon.itemId,'great_axe');assert.equal(inventoryBuild.offhand,null);assert.deepEqual(inventoryStash.map(slot=>slot.item),['old_sword','shield'],'Equipaggiare una due mani deve conservare entrambi gli oggetti sostituiti');
assert.equal(inventory.stableDepositItem(inventoryBuild,inventoryStash,1),true);assert.equal(inventoryStash.at(-1).count,2);assert.equal(inventory.stableWithdrawItem(inventoryBuild,inventoryStash,inventoryStash.length-1),true);assert.equal(inventoryBuild.bag[0].item,'potion','Un consumabile deve completare il tragitto Bag → deposito → Bag');
inventoryStash.push({item:'bow',count:1});assert.equal(inventory.stableWithdrawItem(inventoryBuild,inventoryStash,inventoryStash.length-1),false,'Un eroe non deve ritirare Equipment incompatibile');
assert.equal(inventory.stableDeleteInventory(inventoryBuild,inventoryStash,'bag',0),true);assert.equal(inventoryBuild.bag[0],null,'Eliminare dalla Bag deve liberare lo slot');
assert.equal(inventory.stableDeleteInventory(inventoryBuild,inventoryStash,'stash',0),true);assert.equal(inventory.stableDeleteEquipped(inventoryBuild,'weapon'),true);assert.equal(inventoryBuild.weapon,null);assert.equal(inventoryBuild.twoHanded,false,'Eliminare un’arma a due mani deve liberare correttamente Equipment');
const armorBuild={role:'warrior',maxHp:10,hp:7,armor:null,bag:[{item:'warrior_armor',count:1}]},armorStash=[];
assert.equal(inventory.stableEquipFromBag(armorBuild,armorStash,0),true);assert.equal(armorBuild.armor.itemId,'warrior_armor');assert.deepEqual({hp:armorBuild.hp,maxHp:armorBuild.maxHp},{hp:9,maxHp:12},'Equipaggiare l’armatura deve applicare il bonus Vita una sola volta');
assert.equal(inventory.stableDeleteEquipped(armorBuild,'armor'),true);assert.deepEqual({hp:armorBuild.hp,maxHp:armorBuild.maxHp},{hp:7,maxHp:10},'Rimuovere l’armatura deve togliere il bonus senza alterare la Vita base');
const wrongArmorBuild={role:'mage',maxHp:8,hp:8,armor:null,bag:[{item:'warrior_armor',count:1}]};assert.equal(inventory.stableEquipFromBag(wrongArmorBuild,[],0),false,'Una classe non deve equipaggiare l’armatura di un’altra classe');

const respecNames=['stableTalentPoints','stableTalentTierOpen','stableRemoveCopies','stableStartRespec','stableInvestTalent'];
const respecSource=respecNames.map(name=>board.match(new RegExp(`function ${name}\\([^\\n]+`))?.[0]).join('\n');
const respecTalents={warrior:{root:{cost:3,tier:1,branch:'sword'},cap:{cost:1,tier:2,branch:'sword'}}},respecCards={root:['root_card','root_card'],cap:['cap_card']};
const respec=new Function('TALENTS_BY_ROLE','talentCards',`${respecSource};return{stableTalentPoints,stableStartRespec,stableInvestTalent}`)(respecTalents,(role,id)=>respecCards[id]||[]),respecBuild={role:'warrior',talents:{root:3,cap:1},collection:['base','root_card','root_card','cap_card'],deck:['base','root_card','cap_card'],maxHp:10,hp:10};
assert.equal(respec.stableStartRespec(respecBuild),4);assert.deepEqual(respecBuild.talents,{root:0,cap:0});assert.deepEqual(respecBuild.collection,['base']);assert.deepEqual(respecBuild.deck,['base'],'Il respec deve togliere dal mazzo e dalla collezione le carte dei vecchi talenti');
assert.equal(respec.stableInvestTalent(respecBuild,'cap',4),false,'Un talento di secondo livello non deve ignorare i requisiti del ramo');
assert.equal(respec.stableInvestTalent(respecBuild,'root',4),true);assert.equal(respec.stableInvestTalent(respecBuild,'root',4),true);assert.equal(respec.stableInvestTalent(respecBuild,'root',4),true);assert.equal(respec.stableInvestTalent(respecBuild,'cap',4),true);assert.equal(respec.stableTalentPoints(respecBuild),4);assert.deepEqual(respecBuild.collection,['base','root_card','root_card','cap_card'],'La nuova distribuzione deve restituire soltanto le carte sbloccate dai nuovi talenti');

const talentTreesLiteral=board.match(/const TALENT_TREES=(\{[\s\S]*?\n\});\nfor\(const\[role,tree\]/)?.[1];
assert.ok(talentTreesLiteral,'Gli alberi dei talenti devono essere leggibili dal test');
const talentTrees=new Function(`return ${talentTreesLiteral}`)(),expectedRows=[2,3,2,3,2,1];
assert.equal(Object.keys(talentTrees).length,8,'Devono esistere alberi completi per tutte le otto classi');
for(const[role,tree]of Object.entries(talentTrees)){assert.equal(tree.branches.length,2,`${role} deve avere due specializzazioni`);for(const branch of tree.branches){assert.equal(branch.nodes.length,13,`${role}/${branch.key} deve avere 13 talenti`);assert.deepEqual(Array.from({length:6},(_,index)=>branch.nodes.filter(([,row])=>row===index+1).length),expectedRows,`${role}/${branch.key} deve seguire 2–3–2–3–2–1`)}}
assert.match(board,/function talentTierRequirement\(tier\)\{return Math\.max\(0,\(Number\(tier\)\|\|1\)-1\)\*3\}/,'Le sei righe devono aprirsi ogni tre punti nel ramo');
assert.match(board,/function talentBoost\(h,card,effect\)[^\n]+talent\.boost\?\.\[effect\]\?\.includes\(card\)/,'I nuovi passivi devono modificare le abilità esistenti attraverso un unico calcolo condiviso');
assert.doesNotMatch(board,/warrior:\{[^}]*vanguard:|healer:\{[^}]*renewed_hope:|hunter:\{[^}]*expose_prey:/,'I nuovi passivi non devono aggiungere carte ai mazzi');
assert.match(board,/classic_assault[^\n]+warrior:'protection',healer:'holy',rogue:'subtlety',mage:'fire'/,'Il benchmark Assalto classico deve conservare tank e guaritore');
assert.match(board,/wild_assault[^\n]+paladin:'protection',shaman:'tidebinding',warlock:'demonology',hunter:'wildsnare'/,'Il benchmark Assalto selvaggio deve conservare tank e guaritore');
assert.match(board,/roomClearTurnPending\)\{const hero=game\.party\.find[\s\S]*advanceHeroTurn\(game\)[\s\S]*else activateInitiativeSlot\(game\)/,'Il benchmark completo deve terminare i turni residui dopo aver raccolto i tesori');
assert.match(board,/roomClearTurnPending&&aiControls\(g,g\.activeRole\)\)return\(\)=>aiChooseAndApply\(g\)/,'L IA deve poter usare le azioni residue dopo l ultimo nemico');
assert.match(board,/roomClearTurnPending\)\{const hero=game\.party\.find[\s\S]*hero&&hero\.actions>0\)aiBenchmarkStep\(game\)/,'Il benchmark completo deve usare le azioni residue invece di azzerarle');
assert.match(board,/card==='stillness'\)chosen=h\.stillnessArmed\?null:h;[\s\S]*card==='retreat_roll'\)chosen=reachable\('hunter_bow'\)\?null:h;[\s\S]*card==='predator_storm'\)chosen=hunterMarkedEnemy\(g\)\?h:null/,'L IA Hunter deve poter usare le carte personali invece di cercare un bersaglio nemico');
assert.match(board,/paladin:\{[\s\S]*startingDeck:\['crusader_strike','holy_light','holy_light','flash_of_light','flash_of_light','righteous_defense','blessing_protection','consecration','cleanse','judgment'\]/,'Il mazzo iniziale ibrido del Paladino deve contenere quattro cure dirette senza duplicare attacco e provocazione');
assert.match(board,/base_paladin_shield:\{[^}]*healingBonus:1[\s\S]*silver_shield:\{[^}]*healingBonus:2[\s\S]*gold_templar_shield:\{[^}]*healingBonus:3[\s\S]*mythic_templar_shield:\{[^}]*healingBonus:4/,'Gli scudi del Paladino devono scalare anche come focus di cura');
assert.match(board,/function paladinHeal\([^\n]+h\.offhand\?\.healingBonus[\s\S]*source==='holy_light'[\s\S]*secondary[\s\S]*1\+\(h\.talents\?\.infusion_light\|\|0\)/,'Holy Light deve usare il focus dello scudo e distribuire la cura secondaria di Abundant Grace');
assert.match(board,/card==='blessing_protection'[^\n]+heal\(g,'paladin',ally,2,card\)/,'Blessing of Protection deve curare 2 oltre a fornire assorbimento fisico');
assert.match(board,/holyPaladinWithTank=role==='paladin'[\s\S]*\['righteous_defense','avengers_shield','paladin_holy_shield'\]\.includes\(card\)[\s\S]*!holyPaladinWithTank&&enemies\.length/,'Con un Warrior Protection vivo il Paladino Holy non deve provocare né avanzare verso la mischia');
assert.match(board,/card==='divine_favor'[\s\S]*directHealReady[\s\S]*missing>=3[\s\S]*card==='lay_on_hands'[\s\S]*Math\.max\(6,Math\.ceil\(ally\.maxHp\*\.35\)\)/,'L IA deve conservare Divine Favor e Lay on Hands per cure che ne sfruttano davvero il valore');
const recoveryAiSource=board.match(/function aiRecoveryStep\([^\n]+/)?.[0]||'';
assert.doesNotMatch(recoveryAiSource,/playPaladinCard|holy_light|flash_of_light|holy_shock|lay_on_hands/,'Il Paladino non deve usare abilita durante il turno di Recupero');
assert.match(board,/play=function\(g,h,card,targetValue\)\{\s*if\(g\.playerBoardEnabled&&g\.state==='restoring'\)return false/,'Nessuna abilita deve essere utilizzabile durante il turno di Recupero');
assert.match(board,/function startRecoveryTurn\(g\)\{let restored=0;g\.party\.forEach\(h=>\{if\(h\.hp>0\)\{const before=h\.hp;h\.hp=Math\.min\(h\.maxHp,h\.hp\+4\)/,'Il Campo deve curare automaticamente fino a 4 HP ogni Eroe vivo');
assert.match(board,/Riposo già applicato: fino a \+4 HP per Eroe vivo · nessuna abilità/,'Il Recupero deve spiegare la cura passiva senza suggerire l uso di abilita');

console.log('Balance regression checks passed.');
