const assert=require('node:assert/strict');
const fs=require('node:fs');

const board=fs.readFileSync('player-board.js','utf8');
const bench=fs.readFileSync('dps-bench.js','utf8');
const dungeon=fs.readFileSync('fixed-dungeon.js','utf8');
const connected=fs.readFileSync('connected-rooms.js','utf8');
const profile=fs.readFileSync('profile-storage.js','utf8');
const html=fs.readFileSync('index.html','utf8');

assert.match(board,/warlockShadowPower\(h,3,card\)/,'Void Needle deve partire da 3');
assert.match(board,/corruption'\)\{dealt=warlockDotHit/,'Rot Seed deve colpire subito');
assert.match(board,/piercing_shot'\)dealt=.*hunterMarked\?1:0/,'Piercing Shot deve ricevere +1 dal Braccato');
assert.match(board,/fang_command'\).*hunterMarked\?1\+/,'Fang Command deve ricevere +1 dal Braccato');
assert.doesNotMatch(board,/startRecoveryTurn\([^)]*\).*stripWounds/s,'Il Recupero non deve cancellare le Ferite');
assert.match(board,/warchief:.*special:.*longCast:true/,'La Cascata di Acido deve essere un Cast Lungo');
assert.match(board,/if\(e\.megaBombCasting&&\(e\.longCastReadyRound\|\|0\)<=g\.round\).*turn\.cards=\['special'\]/,'Il Cast Lungo deve completarsi dal turno successivo');
assert.match(board,/type:'engineerBomb'.*megaBombCasting:true.*longCast:'mega_bomb'/,'La bomba deve essere interrompibile');
assert.match(board,/g\.state==='playing'&&h\.consumableTurnUsed/,'I consumabili devono avere il limite per turno');
assert.match(bench,/warlock:\[\['shadow_bolt','Void Needle',3\]/,'Il benchmark deve usare Void Needle da 3');
assert.match(bench,/shadow_mastery'\)\*ticks/,'Il benchmark deve applicare Shadow Mastery a ogni tick dei DoT');
assert.match(board,/function overlordEnemyActivationIds\(g\)/,'Il benchmark deve poter variare il numero di attivazioni nemiche');
assert.match(board,/!repeatedOverlordAction\(g\)&&tickWarlockEnemyEffects/,'I DoT devono scattare una volta per turno nemico, non per azione');
assert.match(board,/runEnemyActionBenchmark/,'Deve esistere il confronto reale tra una e due azioni nemiche');
assert.match(board,/longCastReadyRound=g\.round\+1/,'Il Cast Lungo deve lasciare una finestra di interruzione anche con due azioni');
assert.match(board,/enemyUniqueActions&&repeatedOverlordAction/,'La variante deve impedire due Command uguali nello stesso turno nemico');
assert.match(board,/function enemyCommandPlayable\(g,e,action[^\n]+lastChoiceByEnemy/,'La seconda Command uguale deve risultare disabilitata anche nell’interfaccia');
assert.match(board,/Spedizione reale: stessa compagnia, HP, Ferite, Bag, equip, livelli, talenti e mazzo/,'Il benchmark deve concatenare l’intera spedizione');
assert.match(board,/classic_guard[\s\S]*classic_assault[\s\S]*wild_guard[\s\S]*wild_assault/,'Il benchmark deve coprire tutte le classi e i rami');
assert.match(board,/two_low.*2 Command diverse · 40% danno · 1 Ferita\/round.*enemyActions:2,enemyDamageMultiplier:\.4,enemyWoundCapPerRound:1/,'Il benchmark spedizione deve provare due Command al 40%');
assert.match(board,/two_lower.*2 Command diverse · 35% danno · 1 Ferita\/round.*enemyActions:2,enemyDamageMultiplier:\.35,enemyWoundCapPerRound:1/,'Il benchmark spedizione deve provare due Command al 35%');
assert.match(board,/game\.enemyDamageMultiplier=mode\.enemyDamageMultiplier\|\|1;game\.enemyWoundCapPerRound=mode\.enemyWoundCapPerRound;game\.enemyUniqueActions=mode\.uniqueEnemyActions/,'Il benchmark spedizione deve applicare danno e limite Ferite della variante');
assert.match(board,/cap-g\.enemyWoundsApplied/,'Le Tactic devono poter limitare le Ferite complessive del round');
assert.match(board,/const every=Math\.max\(1,Number\(g\.enemyBonusActivationEvery\)\|\|1\),bonus=\(g\.round\|\|1\)%every\?0:/,'Il motore deve conservare il supporto per la cadenza configurata');
assert.match(board,/hero\.deck\.filter\(card=>card==='wound'\)\.length/,'Il benchmark spedizione deve misurare le Ferite persistenti');
assert.match(board,/delete g\.aiRecoveryDoneRoles;finishRecoveryTurn\(g\)/,'L’AI deve poter terminare il Recupero e proseguire la spedizione');
assert.match(board,/composition\.offers\.find\(entry=>entry\.targetId===destination\)\|\|composition\.offers\.find\(entry=>!g\.temple\.visited\.includes\(entry\.targetId\)\)/,'L’AI deve scegliere una delle due stanze realmente offerte');
assert.match(board,/if\(g\.state!=='loot'\)g\.lootReturnState=g\.state/,'Una seconda ricompensa non deve intrappolare lo stato nel loot');
assert.match(board,/game\.benchmarkMode\|\|gameModalOpen\(\)/,'Il timer UI non deve interferire con il benchmark');
assert.match(board,/game\?\.benchmarkMode\|\|!gameSfxEnabled\(\)/,'L’audio non deve consumare casualità durante il benchmark');
assert.match(board,/game\.state==='loot'\)\{aiLootStep\(game\);acted=true\}/,'Il benchmark deve distribuire il loot senza attendere timer UI');
assert.match(board,/!taker\|\|!assignLoot\(g,loot\.uid,taker\.role\)\)leaveLoot/,'L’AI deve scartare un loot che non riesce ad assegnare');
assert.match(board,/id:'hardcore'.*hpScale:2,damageScale:2,fungi:\{tick:2,boom:8\}/,'Hardcore deve mantenere HP doppi e danni ricalibrati');
assert.match(board,/game\.enemyActionsPerTurn=2;game\.enemyBonusActivationsPerTurn=0;game\.enemyBonusActivationEvery=1;game\.enemyUniqueActions=true;game\.enemyDamageMultiplier=\.35;game\.enemyWoundCapPerRound=1/,'La campagna deve usare due Command diverse con danno e Ferite ricalibrati');
assert.match(board,/game\.tutorial=true;game\.xpHalved=false;game\.enemyActionsPerTurn=1;game\.enemyBonusActivationsPerTurn=0;game\.enemyUniqueActions=false;game\.enemyDamageMultiplier=1;delete game\.enemyWoundCapPerRound/,'Il tutorial deve restare a una Command con danno pieno');
assert.match(dungeon,/id:'deep-gate'[\s\S]*terrainLayout:\{rows:5,cols:5/,'L’Ala Profonda deve iniziare su una griglia 5×5');
assert.match(dungeon,/id:'deep-gate'[\s\S]*name:'Le Porte di Radicava'[\s\S]*siege:true[\s\S]*hp:10,rounds:3[\s\S]*rewardWeapons:3/,'Radicava deve essere un assedio da tre ondate con tre armi Normal');
assert.match(dungeon,/id:'deep-cistern'[\s\S]*name:'Il Ponte delle Cisterne'[\s\S]*hp:14,rounds:4[\s\S]*rewardTier:'GOLD'[\s\S]*terrainLayout:\{rows:5,cols:5/,'Il secondo fronte deve essere un assedio Heroic 5×5 da quattro ondate');
assert.match(dungeon,/id:'deep-roots'[\s\S]*name:'Il Bastione delle Radici'[\s\S]*hp:18,rounds:5[\s\S]*damagePerEnemy:3[\s\S]*rewardTier:'GOLD2'[\s\S]*terrainLayout:\{rows:5,cols:5/,'Il terzo fronte deve essere un assedio Hardcore 5×5 da cinque ondate');
assert.doesNotMatch(dungeon,/id:'deep-defense'|id:'deep-heart'/,'Il vertical slice non deve conservare le vecchie stanze scollegate');
assert.match(connected,/fixedCampaignEntranceId\(g\.campaignWing\)/,'L’ingresso deve dipendere dallo scenario di assedio selezionato');
assert.match(board,/freshGame\.campaignWing=meta\?\.wing\|\|'temple'/,'La campagna deve conservare l’ala scelta');
assert.match(board,/Math\.max\(5,Math\.min\(10,\+g\?\.combatGridCols\|\|6\)\)/,'La griglia reale deve accettare cinque colonne');
assert.match(board,/if\(target\.boss\)forceTempleBossTile/,'Qualsiasi finale dichiarato deve materializzare il boss');
assert.match(board,/if\(isSiegeWing\(g\.campaignWing\)\)j\.deepWingCleared=true/,'La vittoria nell’assedio non deve alterare lo sblocco delle difficoltà del Tempio');
assert.match(board,/function revealSiegeWeaponLoot\(g,count=3,tier='SILVER',label='NORMAL',diff='normale'\)[\s\S]*kind==='equipment'&&item\.slot!=='offhand'[\s\S]*pendingLootLabel=label/,'L’assedio deve rivelare tre armi del tier richiesto e compatibili');
assert.match(board,/const SIEGE_LEVELS=\[[\s\S]*id:'profonda'[\s\S]*id:'profonda-heroic'[\s\S]*id:'profonda-hardcore'/,'I tre assedi devono essere sempre disponibili');
assert.match(board,/function deepWingButtonHtml\(\)[\s\S]*SIEGE_LEVELS\.map[\s\S]*data-siege-level/,'Gli assedi devono essere sempre selezionabili');
assert.match(board,/hardcoreFungi=\['hardcore','profonda-hardcore'\]\.includes\(g\.difficulty\)/,'I funghi dell’assedio Hardcore devono aggiungere Ferite persistenti');
assert.match(board,/function defenseWaveForecast\(g\)[\s\S]*defenseSpawnCells\(g,tokens\.length\)[\s\S]*data-wave-preview/,'La griglia deve anticipare posizione e tipo dei nemici della prossima ondata');
assert.match(board,/if\(plan\.siege\)g\.siegeDeployment=\{selectedRole:[\s\S]*function siegeDeploymentCells\(g,role=[\s\S]*function confirmSiegeDeployment\(g\)/,'Ogni assedio deve iniziare con uno schieramento gratuito nella metà difensiva');
assert.match(board,/function bindSiegeDeployment\(shell,g\)[\s\S]*data-siege-deploy-confirm[\s\S]*if\(g\.siegeDeployment\)bindSiegeDeployment/,'La griglia deve permettere di posizionare gli eroi e confermare lo schieramento');
assert.match(board,/if\(g\.siegeDeployment\)shell\.querySelectorAll\('\.real-hero-slot button'\)[\s\S]*button\.disabled=true/,'Durante lo schieramento nessuna azione normale deve essere utilizzabile');
assert.match(board,/if\(g\.siegeDeployment\)return aliveAiHeroesOnly\(g\)\?\(\)=>confirmSiegeDeployment\(g\):null/,'Una compagnia interamente AI non deve bloccarsi nello schieramento');
assert.match(board,/objective\?\.siege\?\(origin\.col-cell\.col\)\*1000-Math\.abs\(origin\.row-cell\.row\)\*20:0/,'Nell’assedio i nemici senza attacchi validi devono avanzare verso il Bastione restando nella propria corsia');
assert.match(board,/objective\.siege&&wave>1\)\{g\.siegeWaveAnnouncement=[\s\S]*function showSiegeWaveAnnounce\(g,onDone\)/,'Le ondate successive devono avere un annuncio compatto con la propria composizione');
assert.match(board,/objective\.siege&&wave>1\)\{[\s\S]*hero\.siegeRallyWave=wave[\s\S]*Rally · 1 movimento gratuito per Eroe/,'Dalla seconda ondata ogni Eroe vivo deve ricevere un movimento Rally gratuito');
assert.match(board,/rally\?'✥ Muovi · RALLY'[\s\S]*if\(rally\)hero\.siegeRallyWave=null/,'Il movimento Rally deve essere visibile e consumarsi senza spendere azioni');
assert.match(board,/function siegeEnemyThreat\(g,enemy\)[\s\S]*enemyMoveDestination\(g,enemy\)\?\.col<=objective\.breachCol/,'L’Assedio deve riconoscere i nemici già alla breccia o a un movimento di distanza');
assert.match(board,/siege-threat-badge[\s\S]*ALLA BRECCIA[\s\S]*1 AVANZATA[\s\S]*⚠ Breccia:/,'Le minacce immediate devono essere visibili sia sulle carte sia nel pannello obiettivo');
assert.match(board,/if\(g\.siegeWaveAnnouncement\)return null/,'L’AI deve attendere la fine dell’annuncio della nuova ondata');
assert.match(dungeon,/deep-gate[\s\S]*fortifyPower:2[\s\S]*deep-cistern[\s\S]*Funghi del Miasma[\s\S]*deep-roots[\s\S]*2 Ferite/,'I tre Assedi devono dichiarare regole di campo diverse');
assert.match(board,/room\.heroExitTreasure>0\|\|activeDefenseObjective\(g\)\?\.siege/,'I Funghi devono attivarsi anche negli Assedi senza tesori');
assert.match(board,/power=objective\.fortifyPower\|\|1[\s\S]*objective\.block\+=power/,'Le barricate di Radicava devono applicare il proprio valore di Fortifica');
assert.match(board,/g\.siegeBreachFx=\{attackers:attackers\.length,damage,blocked\}[\s\S]*enemy\.breached=true;enemy\.hp=0/,'Lo sfondamento deve conservare i dati dell’impatto e distinguersi dalla morte del nemico');
assert.match(board,/siege-breach-damage[\s\S]*INTEGRITÀ[\s\S]*BLOCCATO/,'La carta obiettivo deve mostrare danno o parata dello sfondamento');
assert.match(board,/objective\.siege\?objective\.wave>=objective\.rounds&&!aliveEnemies\(g\)\.length:g\.round>=objective\.rounds/,'L’Assedio deve terminare solo dopo l’ultima ondata e con la griglia ripulita');
assert.match(board,/if\(!objective\.siege\|\|objective\.wave<objective\.rounds\)spawnDefenseWave/,'Dopo l’ultima ondata non devono comparire altri nemici');
assert.match(dungeon,/deep-gate[\s\S]*obstacles:\[\{row:2,col:3\},\{row:4,col:3\}\][\s\S]*deep-cistern[\s\S]*obstacles:\[\{row:1,col:3\},\{row:5,col:3\}\][\s\S]*deep-roots[\s\S]*obstacles:\[\{row:2,col:3\},\{row:3,col:3\},\{row:4,col:3\}\]/,'I tre Assedi devono avere geometrie di corsia differenti');
assert.match(board,/function combatGridObstacleKeys\(g\)[\s\S]*combatGridObstacleKeys\(g\)[\s\S]*grid-obstacle/,'Le celle ostacolo devono essere condivise da movimento, spawn e rendering');
assert.match(board,/id="menuStable">Scuderia/,'Il menu deve aprire la Scuderia');
assert.match(board,/function createStable\(menu\)/,'La Scuderia deve avere una vista dedicata');
assert.match(board,/HERO_CLASSES\.map\(hero=>stableHeroCard\(hero,heroes,selectedRoles\)\)/,'La Scuderia deve mostrare tutte le otto classi e la formazione salvata');
assert.match(board,/window\.RaidProfile\?\.load\(localStorage\)/,'La Scuderia deve leggere il profilo persistente');
assert.match(board,/build\?\.heroLevel[\s\S]*build\?\.xp[\s\S]*build\?\.deck[\s\S]*build\?\.collection/,'Le schede devono mostrare progressione e stato del mazzo reali');
assert.match(board,/specialization=developed\?stableSpecialization\(role,build\)[\s\S]*equipment=developed\?stableEscape\(stableEquipment\(build\)\)/,'Le schede devono mostrare specializzazione ed equipaggiamento reali');
assert.match(board,/account=loadAccount\(\),accountHeroes=account\?\.heroes\|\|\{\}/,'La formazione della compagnia deve leggere gli eroi dalla Scuderia');
assert.match(board,/roles\.map\(role=>accountHeroes\[role\]\)\.filter\(Boolean\);startLevel\(level,roles,roster/,'La nuova spedizione deve portare le build degli eroi selezionati');
assert.match(board,/account\?\.unlocks\?\.raidDifficultyIndex\|\|0/,'Le difficoltà sbloccate devono appartenere al profilo e non alla singola spedizione');
assert.match(board,/Livelli, talenti, mazzi ed equipaggiamenti resteranno nella Scuderia/,'Cambiare compagnia deve dichiarare che la progressione non viene cancellata');
assert.match(board,/function recoveredAccountBuild\(h\)[^\n]+build\.hp=build\.maxHp[^\n]+filter\(card=>card!=='wound'\)/,'Dopo una sconfitta la Scuderia deve conservare la build ma ripristinare vita e Ferite');
assert.match(board,/function persistAccountOnLoss\(g\)[^\n]+saveAccountHeroes\(roster,g\.companyName\|\|''\);recordAccountRun\('loss',g\);clearJourney\(\)/,'La sconfitta deve aggiornare la carriera, la Scuderia e chiudere la spedizione fallita');
assert.match(board,/game\.state==='lost'&&!game\.__accountLossSaved&&!game\.tutorial&&!game\.benchmarkMode&&!game\.combatGridScenario/,'Il salvataggio della sconfitta deve avvenire una sola volta e non contaminare tutorial o simulatori');
assert.match(board,/Progressi salvati nella Scuderia/,'La vittoria deve confermare il salvataggio nel riepilogo');
assert.match(board,/function stableDeckChange\(build,card,delta\)/,'La Scuderia deve consentire gli scambi del mazzo fuori dalla spedizione');
assert.match(board,/cleanSize>=DECK_CAP\|\|\(used\[card\]\|\|0\)>=DECK_COPY_MAX\|\|!\(available\[card\]>0\)/,'Gli scambi devono rispettare capienza, copie massime e carte possedute');
assert.match(board,/locked=!!profile\?\.activeJourney[\s\S]*Spedizione in corso: la scheda è in sola lettura/,'Una spedizione attiva deve bloccare le modifiche concorrenti della Scuderia');
assert.match(board,/RaidProfile\?\.write\(localStorage,profile\)/,'Le modifiche confermate devono essere salvate nel profilo senza toccare gli altri eroi');
assert.match(board,/function stableDepositItem\(build,stash,index\)/,'La Scuderia deve poter spostare oggetti dalla Bag al deposito comune');
assert.match(board,/function stableWithdrawItem\(build,stash,index\)/,'La Scuderia deve poter assegnare gli oggetti del deposito a un eroe compatibile');
assert.match(board,/function stableEquipFromBag\(build,stash,index,hand='left'\)/,'La Scuderia deve poter cambiare Equipment e conservare l’oggetto sostituito');
assert.match(board,/profile\.heroes\[currentRole\]=JSON\.parse\(JSON\.stringify\(draft\)\);profile\.stash=JSON\.parse\(JSON\.stringify\(stashDraft\)\)/,'Bag, Equipment e deposito devono essere salvati insieme nel profilo');
assert.match(board,/if\(locked&&draft\)\{renderDraft\(profile\);return\}/,'La spedizione attiva deve bloccare anche le modifiche all’inventario');
assert.match(board,/data-stable-roster=/,'La scheda eroe deve permettere di aggiungere o rimuovere l’eroe dalla formazione');
assert.match(board,/selected=new Set\(\(account\?\.selectedRoles\|\|\[\]\)\.filter/,'La nuova campagna deve proporre la formazione salvata');
assert.match(board,/profile\.selectedRoles=\[\.\.\.roles\];RaidProfile\.write\(localStorage,profile\)/,'Avviare una campagna deve salvare la formazione scelta');
assert.doesNotMatch(profile,/function clearProfileJourney\([^\n]+selectedRoles=\[\]/,'Terminare la spedizione non deve cancellare la formazione preferita');
assert.match(board,/function profileSummaryData\(profile\)/,'La home deve ricavare il riepilogo dal profilo persistente');
assert.match(board,/RaidProfile\?\.milestone\(profile\)[\s\S]*goal\.rank[\s\S]*goal\.label/,'La home deve mostrare il prossimo obiettivo della compagnia');
assert.match(board,/recordAccountRun\('win',g\)/,'Una vittoria deve aggiornare la carriera della compagnia');
assert.match(board,/stats\?\.heroes\?\.\[role\]/,'La Scuderia deve mostrare quante spedizioni ha giocato ogni eroe');
assert.match(board,/data-stable-hero-name[\s\S]*draft\.playerName=event\.target\.value\.trimStart\(\)\.slice\(0,24\)/,'La Scuderia deve permettere di rinominare un eroe sviluppato');
assert.match(board,/data-menu-profile[\s\S]*PROFILO COMPAGNIA/,'La home deve mostrare il riepilogo della compagnia');
assert.match(board,/data-stable-company-save[\s\S]*profile\.company=name;[\s\S]*RaidProfile\?\.write\(localStorage,profile\)/,'La Scuderia deve permettere di salvare il nome della compagnia');
assert.match(board,/new MutationObserver\(\(\)=>\{if\(!menu\.hidden\)syncProfile\(\)\}\)/,'Il riepilogo deve aggiornarsi quando si torna alla home');
assert.match(board,/\.hero-select-setup\{overflow:hidden/,'La selezione della spedizione non deve scorrere come una pagina HTML');
assert.match(board,/setSetupHeading=level=>[\s\S]*Scegli la spedizione[\s\S]*setSetupHeading\(true\)/,'La seconda pagina deve mostrare il titolo della spedizione');
assert.match(html,/\.setup-level-page\{display:flex!important[\s\S]*grid-template-columns:repeat\(3/,'Le sei spedizioni devono occupare una griglia centrale 3×2');
assert.match(board,/\.setup-page\[hidden\]\{display:none\}/,'Compagnia e spedizione non devono occupare insieme lo stesso viewport');
assert.match(board,/data-setup-party[\s\S]*data-setup-level hidden/,'Compagnia e spedizione devono vivere in due viste fisse');
assert.match(board,/\.main-menu\{overflow:hidden\}/,'Anche la home deve essere una schermata fissa senza scorrimento');
assert.match(board,/\.stable-overlay\{[^}]*overflow:hidden/,'La Scuderia deve restare dentro il viewport');
assert.match(board,/data-stable-tab="hero"[\s\S]*data-stable-tab="equipment"[\s\S]*data-stable-tab="deck"/,'La scheda eroe deve usare sezioni invece dello scorrimento');
assert.match(board,/const pager=\(page,pages\)/,'Liste lunghe di Bag, deposito e mazzo devono usare pagine');
assert.match(board,/data-stable-export>Esporta profilo[\s\S]*data-stable-import>Importa profilo/,'La Scuderia deve poter esportare e importare il profilo');
assert.match(board,/RaidProfile\?\.normalize\(parsed\?\.profile\|\|parsed\)[\s\S]*confirm\(`/,'Un backup deve essere validato e confermato prima di sostituire il profilo');

const inventoryNames=['stableItemFitsRole','stableEnsureBag','stableStoreItem','stableDepositItem','stableWithdrawItem','stableBagCanTake','stableEquipFromBag'];
const inventorySource=inventoryNames.map(name=>board.match(new RegExp(`function ${name}\\([^\\n]+`))?.[0]).join('\n');
const inventory=new Function('HERO_BAG_SLOTS','bagStackable','TREASURE_ITEMS','equipmentFromItem',`${inventorySource};return{stableDepositItem,stableWithdrawItem,stableEquipFromBag}`)(9,id=>id==='potion',{potion:{kind:'consumable'},old_sword:{name:'Sword',kind:'equipment',role:'warrior',slot:'weapon'},great_axe:{name:'Greataxe',kind:'equipment',role:'warrior',slot:'weapon',twoHanded:true},shield:{name:'Shield',kind:'equipment',role:'warrior',slot:'offhand'},bow:{name:'Bow',kind:'equipment',role:'hunter',slot:'weapon'}},(id,diff)=>({itemId:id,name:id,twoHanded:id==='great_axe',acqDiff:diff||null}));
const inventoryBuild={role:'warrior',weapon:{itemId:'old_sword'},offhand:{itemId:'shield'},twoHanded:false,bag:[{item:'great_axe',count:1},{item:'potion',count:2}]},inventoryStash=[];
assert.equal(inventory.stableEquipFromBag(inventoryBuild,inventoryStash,0),true);assert.equal(inventoryBuild.weapon.itemId,'great_axe');assert.equal(inventoryBuild.offhand,null);assert.deepEqual(inventoryStash.map(slot=>slot.item),['old_sword','shield'],'Equipaggiare una due mani deve conservare entrambi gli oggetti sostituiti');
assert.equal(inventory.stableDepositItem(inventoryBuild,inventoryStash,1),true);assert.equal(inventoryStash.at(-1).count,2);assert.equal(inventory.stableWithdrawItem(inventoryBuild,inventoryStash,inventoryStash.length-1),true);assert.equal(inventoryBuild.bag[0].item,'potion','Un consumabile deve completare il tragitto Bag → deposito → Bag');
inventoryStash.push({item:'bow',count:1});assert.equal(inventory.stableWithdrawItem(inventoryBuild,inventoryStash,inventoryStash.length-1),false,'Un eroe non deve ritirare Equipment incompatibile');

console.log('Balance regression checks passed.');
