const assert=require('node:assert/strict');
const fs=require('node:fs');

const board=fs.readFileSync('player-board.js','utf8');
const bench=fs.readFileSync('dps-bench.js','utf8');
const dungeon=fs.readFileSync('fixed-dungeon.js','utf8');
const connected=fs.readFileSync('connected-rooms.js','utf8');

assert.match(board,/warlockShadowPower\(h,3,card\)/,'Void Needle deve partire da 3');
assert.match(board,/corruption'\)\{dealt=warlockDotHit/,'Rot Seed deve colpire subito');
assert.match(board,/piercing_shot'\)dealt=.*hunterMarked\?1:0/,'Piercing Shot deve ricevere +1 dal Braccato');
assert.match(board,/fang_command'\).*hunterMarked\?1\+/,'Fang Command deve ricevere +1 dal Braccato');
assert.doesNotMatch(board,/startRecoveryTurn\([^)]*\).*stripWounds/s,'Il Recupero non deve cancellare le Ferite');
assert.match(board,/warchief:.*special:.*longCast:true/,'La Cascata di Acido deve essere un Cast Lungo');
assert.match(board,/if\(e\.megaBombCasting&&\(e\.longCastReadyRound\|\|0\)<=g\.round\).*turn\.cards=\['special'\]/,'Il Cast Lungo deve completarsi dal turno successivo');
assert.match(board,/type:'engineerBomb'.*megaBombCasting:true.*longCast:'mega_bomb'/,'La bomba deve essere interrompibile');
assert.match(board,/g\.state==='playing'&&h\.consumableTurnUsed/,'I consumabili devono avere il limite per turno');
assert.match(bench,/warlock:\[\['shadow_bolt','Void Needle',3\]/,'Il benchmark deve usare Void Needle da 3');
assert.match(bench,/shadow_mastery'\)\*ticks/,'Il benchmark deve applicare Shadow Mastery a ogni tick dei DoT');
assert.match(board,/function overlordEnemyActivationIds\(g\)/,'Il benchmark deve poter variare il numero di attivazioni nemiche');
assert.match(board,/!repeatedOverlordAction\(g\)&&tickWarlockEnemyEffects/,'I DoT devono scattare una volta per turno nemico, non per azione');
assert.match(board,/runEnemyActionBenchmark/,'Deve esistere il confronto reale tra una e due azioni nemiche');
assert.match(board,/longCastReadyRound=g\.round\+1/,'Il Cast Lungo deve lasciare una finestra di interruzione anche con due azioni');
assert.match(board,/enemyUniqueActions&&repeatedOverlordAction/,'La variante deve impedire due Command uguali nello stesso turno nemico');
assert.match(board,/function enemyCommandPlayable\(g,e,action[^\n]+lastChoiceByEnemy/,'La seconda Command uguale deve risultare disabilitata anche nell’interfaccia');
assert.match(board,/Spedizione reale: stessa compagnia, HP, Ferite, Bag, equip, livelli, talenti e mazzo/,'Il benchmark deve concatenare l’intera spedizione');
assert.match(board,/classic_guard[\s\S]*classic_assault[\s\S]*wild_guard[\s\S]*wild_assault/,'Il benchmark deve coprire tutte le classi e i rami');
assert.match(board,/two_low.*2 Command diverse · 40% danno · 1 Ferita\/round.*enemyActions:2,enemyDamageMultiplier:\.4,enemyWoundCapPerRound:1/,'Il benchmark spedizione deve provare due Command al 40%');
assert.match(board,/two_lower.*2 Command diverse · 35% danno · 1 Ferita\/round.*enemyActions:2,enemyDamageMultiplier:\.35,enemyWoundCapPerRound:1/,'Il benchmark spedizione deve provare due Command al 35%');
assert.match(board,/game\.enemyDamageMultiplier=mode\.enemyDamageMultiplier\|\|1;game\.enemyWoundCapPerRound=mode\.enemyWoundCapPerRound;game\.enemyUniqueActions=mode\.uniqueEnemyActions/,'Il benchmark spedizione deve applicare danno e limite Ferite della variante');
assert.match(board,/cap-g\.enemyWoundsApplied/,'Le Tactic devono poter limitare le Ferite complessive del round');
assert.match(board,/const every=Math\.max\(1,Number\(g\.enemyBonusActivationEvery\)\|\|1\),bonus=\(g\.round\|\|1\)%every\?0:/,'Il motore deve conservare il supporto per la cadenza configurata');
assert.match(board,/hero\.deck\.filter\(card=>card==='wound'\)\.length/,'Il benchmark spedizione deve misurare le Ferite persistenti');
assert.match(board,/delete g\.aiRecoveryDoneRoles;finishRecoveryTurn\(g\)/,'L’AI deve poter terminare il Recupero e proseguire la spedizione');
assert.match(board,/composition\.offers\.find\(entry=>entry\.targetId===destination\)\|\|composition\.offers\.find\(entry=>!g\.temple\.visited\.includes\(entry\.targetId\)\)/,'L’AI deve scegliere una delle due stanze realmente offerte');
assert.match(board,/if\(g\.state!=='loot'\)g\.lootReturnState=g\.state/,'Una seconda ricompensa non deve intrappolare lo stato nel loot');
assert.match(board,/game\.benchmarkMode\|\|gameModalOpen\(\)/,'Il timer UI non deve interferire con il benchmark');
assert.match(board,/game\?\.benchmarkMode\|\|!gameSfxEnabled\(\)/,'L’audio non deve consumare casualità durante il benchmark');
assert.match(board,/game\.state==='loot'\)\{aiLootStep\(game\);acted=true\}/,'Il benchmark deve distribuire il loot senza attendere timer UI');
assert.match(board,/!taker\|\|!assignLoot\(g,loot\.uid,taker\.role\)\)leaveLoot/,'L’AI deve scartare un loot che non riesce ad assegnare');
assert.match(board,/id:'hardcore'.*hpScale:2,damageScale:2,fungi:\{tick:2,boom:8\}/,'Hardcore deve mantenere HP doppi e danni ricalibrati');
assert.match(board,/game\.enemyActionsPerTurn=2;game\.enemyBonusActivationsPerTurn=0;game\.enemyBonusActivationEvery=1;game\.enemyUniqueActions=true;game\.enemyDamageMultiplier=\.35;game\.enemyWoundCapPerRound=1/,'La campagna deve usare due Command diverse con danno e Ferite ricalibrati');
assert.match(board,/game\.tutorial=true;game\.xpHalved=false;game\.enemyActionsPerTurn=1;game\.enemyBonusActivationsPerTurn=0;game\.enemyUniqueActions=false;game\.enemyDamageMultiplier=1;delete game\.enemyWoundCapPerRound/,'Il tutorial deve restare a una Command con danno pieno');
assert.match(dungeon,/id:'deep-gate'[\s\S]*terrainLayout:\{rows:5,cols:5/,'L’Ala Profonda deve iniziare su una griglia 5×5');
assert.match(dungeon,/id:'deep-defense'[\s\S]*objective:\{type:'defense'[\s\S]*terrainLayout:\{rows:6,cols:6/,'La seconda stanza deve essere una difesa 6×6');
assert.match(dungeon,/id:'deep-heart'[\s\S]*boss:'miniBoss'[\s\S]*terrainLayout:\{rows:6,cols:6/,'Il Cuore Sepolto deve chiudere l’ala con un boss 6×6');
assert.match(connected,/g\.campaignWing==='deep'\?'deep-gate':'gate'/,'L’ingresso deve dipendere dall’ala selezionata');
assert.match(board,/freshGame\.campaignWing=meta\?\.wing\|\|'temple'/,'La campagna deve conservare l’ala scelta');
assert.match(board,/Math\.max\(5,Math\.min\(10,\+g\?\.combatGridCols\|\|6\)\)/,'La griglia reale deve accettare cinque colonne');
assert.match(board,/if\(target\.boss\)forceTempleBossTile/,'Qualsiasi finale dichiarato deve materializzare il boss');
assert.match(board,/if\(g\.campaignWing==='deep'\)j\.deepWingCleared=true/,'La vittoria nell’ala non deve alterare lo sblocco delle difficoltà del Tempio');
assert.match(board,/id="menuStable">Scuderia/,'Il menu deve aprire la Scuderia');
assert.match(board,/function createStable\(menu\)/,'La Scuderia deve avere una vista dedicata');
assert.match(board,/HERO_CLASSES\.map\(hero=>stableHeroCard\(hero,heroes\)\)/,'La Scuderia deve mostrare tutte le otto classi disponibili');
assert.match(board,/window\.RaidProfile\?\.load\(localStorage\)/,'La Scuderia deve leggere il profilo persistente');
assert.match(board,/build\?\.heroLevel[\s\S]*build\?\.xp[\s\S]*build\?\.deck[\s\S]*build\?\.collection/,'Le schede devono mostrare progressione e stato del mazzo reali');
assert.match(board,/specialization=developed\?stableSpecialization\(role,build\)[\s\S]*equipment=developed\?stableEscape\(stableEquipment\(build\)\)/,'Le schede devono mostrare specializzazione ed equipaggiamento reali');
assert.match(board,/account=loadAccount\(\),accountHeroes=account\?\.heroes\|\|\{\}/,'La formazione della compagnia deve leggere gli eroi dalla Scuderia');
assert.match(board,/roles\.map\(role=>accountHeroes\[role\]\)\.filter\(Boolean\);startLevel\(level,roles,roster/,'La nuova spedizione deve portare le build degli eroi selezionati');
assert.match(board,/account\?\.unlocks\?\.raidDifficultyIndex\|\|0/,'Le difficoltà sbloccate devono appartenere al profilo e non alla singola spedizione');
assert.match(board,/Livelli, talenti, mazzi ed equipaggiamenti resteranno nella Scuderia/,'Cambiare compagnia deve dichiarare che la progressione non viene cancellata');
assert.match(board,/function recoveredAccountBuild\(h\)[^\n]+build\.hp=build\.maxHp[^\n]+filter\(card=>card!=='wound'\)/,'Dopo una sconfitta la Scuderia deve conservare la build ma ripristinare vita e Ferite');
assert.match(board,/function persistAccountOnLoss\(g\)[^\n]+saveAccountHeroes\(roster,g\.companyName\|\|''\);clearJourney\(\)/,'La sconfitta deve aggiornare la Scuderia e chiudere la spedizione fallita');
assert.match(board,/game\.state==='lost'&&!game\.__accountLossSaved&&!game\.tutorial&&!game\.benchmarkMode&&!game\.combatGridScenario/,'Il salvataggio della sconfitta deve avvenire una sola volta e non contaminare tutorial o simulatori');
assert.match(board,/Progressi salvati nella Scuderia/,'La vittoria deve confermare il salvataggio nel riepilogo');
assert.match(board,/function stableDeckChange\(build,card,delta\)/,'La Scuderia deve consentire gli scambi del mazzo fuori dalla spedizione');
assert.match(board,/cleanSize>=DECK_CAP\|\|\(used\[card\]\|\|0\)>=DECK_COPY_MAX\|\|!\(available\[card\]>0\)/,'Gli scambi devono rispettare capienza, copie massime e carte possedute');
assert.match(board,/profile\?\.activeJourney[\s\S]*puoi consultare la scheda, ma il mazzo si modifica al ritorno/,'Una spedizione attiva deve bloccare le modifiche concorrenti al mazzo');
assert.match(board,/RaidProfile\?\.saveHeroes\(localStorage,\[draft\]/,'Il mazzo confermato deve essere salvato nel profilo senza toccare gli altri eroi');

console.log('Balance regression checks passed.');
