'use strict';

const PLAYER_BOARD_CONFIG={
  warrior:{
    front:{className:'Warrior',specializationName:'Guardian',roleTag:'TANK',artwork:'Artwork Warrior Tank',maxHp:12,passive:'TBD — passiva Tank configurabile',startingDeck:['sword','sword','rend','rend','parry','parry','parry','taunt','taunt','critical'],abilities:['sword','rend','parry','taunt']},
    back:{className:'Warrior',specializationName:'TBD',roleTag:'DPS · TBD',artwork:'Artwork Warrior DPS · TBD',maxHp:12,passive:'TBD',startingDeck:['sword','rend','parry','parry','taunt'],abilities:['sword','rend','parry','taunt'],placeholder:true}
  },
  healer:{
    front:{className:'Priest',specializationName:'Healer',roleTag:'HEALER',artwork:'Artwork Priest Healer',maxHp:8,passive:'Position NEAR / FAR permanente',startingDeck:['quick_heal','quick_heal','slow_heal','slow_heal','slow_heal','bandage','bandage','holy_pulse','holy_pulse','critical'],abilities:['quick_heal','slow_heal','bandage','holy_pulse']},
    back:{className:'Healer',specializationName:'TBD',roleTag:'TBD',artwork:'Artwork Healer retro · TBD',maxHp:8,passive:'TBD',startingDeck:['quick_heal','slow_heal','slow_heal','bandage','holy_pulse'],abilities:['quick_heal','slow_heal','bandage','holy_pulse'],placeholder:true}
  },
  rogue:{
    front:{className:'Rogue',specializationName:'Assassin',roleTag:'DPS',artwork:'Artwork Rogue Assassin',maxHp:9,passive:'Position FRONT / BEHIND permanente',startingDeck:['backstab','backstab','backstab','eviscerate','eviscerate','eviscerate','evasion','evasion','preparation','critical'],abilities:['backstab','eviscerate','evasion','preparation']},
    back:{className:'Rogue',specializationName:'TBD',roleTag:'TBD',artwork:'Artwork Rogue retro · TBD',maxHp:9,passive:'TBD',startingDeck:['backstab','backstab','eviscerate','evasion','preparation'],abilities:['backstab','eviscerate','evasion','preparation'],placeholder:true}
  }
};
const ABILITY_TEXT={
  sword:['1 danno','2 danni','3 danni'],rend:['+1 Bleed: −1 Command alla prossima attivazione','TBD — non attivo','TBD — non attivo'],parry:['Previeni 1','Previeni 2','Previeni 2 + contrattacco'],taunt:['Aggro su 1 nemico','Aggro su 2 nemici','Aggro su tutti i nemici'],
  quick_heal:['Cura 2','Cura 3','Cura 3 su due target'],slow_heal:['Cura 5 canalizzata','Cura 6 canalizzata','Cura 6 divisa su due target'],bandage:['Rimuovi 1 Ferita','Rimuovi 2 Ferite','Rimuovi 1 Ferita da ogni alleato'],holy_pulse:['1 danno','1 danno a 2 nemici','2 danni a 2 nemici']
  ,backstab:['BEHIND: 4 danni','TBD','TBD'],eviscerate:['FRONT: 2 danni; 3 a ≤50% HP','TBD','TBD'],evasion:['ANY: annulla prossimo Attack single-target','TBD','TBD'],preparation:['ANY: pesca 2, scarta 2 Ability','TBD','TBD']
};
Object.assign(NAMES,{rogue:'Rogue',healer:'Priest',backstab:'Backstab',eviscerate:'Eviscerate',evasion:'Evasion',preparation:'Preparation',critical:'Critico'});
Object.assign(DESC,{backstab:'BEHIND only · 4 danni',eviscerate:'FRONT only · 2/3 danni',evasion:'Annulla prossimo Attack single-target',preparation:'Pesca 2, poi scarta 2 Ability',critical:'Abbina gratis alla prossima Ability compatibile'});
DESC.rend='Rend v0.3: +1 Bleed; −1 Command alla prossima attivazione';
const boardAudit=(g,type,data={})=>{g.playerBoardAudit.events.push({type,encounter:g.encounter+1,round:g.round,...data})};
const boardLevel=n=>n>=5?3:n>=2?2:1;
function validateBoard(g){const violations=[];for(const h of g.party){if(h.hp<0||h.hp>h.maxHp)violations.push(`${h.role}: HP ${h.hp}/${h.maxHp}`);for(const [a,n] of Object.entries(h.mastery||{}))if(n<0||n>5)violations.push(`${h.role}.${a}: track ${n}`)}g.playerBoardAudit.consistencyChecks++;g.playerBoardAudit.violations.push(...violations);return violations}
function rogueHero(){return{role:'rogue',abilities:[],hp:9,maxHp:9,deck:[],draw:[],discard:[],hand:[],levels:{},invested:{},casting:null,actions:CONFIG.actionsPerRound,shield:0,counter:0,evasion:false}}
const COMMAND_DECK_V01=['attack','attack','attack','tactic','tactic','special'];
const PLAYER_BOARD_ENEMIES={goblin:{hp:8,damage:6},miniBoss:{hp:20,damage:6}};
function applyPlayerBoardEnemyStats(g){for(const e of g.enemies){const cfg=PLAYER_BOARD_ENEMIES[e.type];if(!cfg)continue;e.hp=e.maxHp=cfg.hp;e.damage=cfg.damage}}
function resetHeroTurn(g){g.turnOrder=['warrior','healer','rogue'];g.activeTurnIndex=0;while(g.activeTurnIndex<g.turnOrder.length&&!aliveHeroes(g).some(h=>h.role===g.turnOrder[g.activeTurnIndex]))g.activeTurnIndex++;g.activeRole=g.turnOrder[g.activeTurnIndex]||null}
function advanceHeroTurn(g){if(!g.playerBoardEnabled||g.state!=='playing')return;const current=g.party.find(h=>h.role===g.activeRole);if(current?.actions>0||current?.preparationPending)return;do g.activeTurnIndex++;while(g.activeTurnIndex<g.turnOrder.length&&!aliveHeroes(g).some(h=>h.role===g.turnOrder[g.activeTurnIndex]));if(g.activeTurnIndex<g.turnOrder.length){g.activeRole=g.turnOrder[g.activeTurnIndex];note(g,`▶ Turno ${NAMES[g.activeRole]}.`);return}g.activeRole='enemies';note(g,'☠ Turno dei nemici.');endRound(g)}
function passHeroTurn(g){const h=g.party.find(hero=>hero.role===g.activeRole);if(!h||h.preparationPending||g.state!=='playing')return false;h.actions=0;note(g,`→ ${NAMES[h.role]} passa.`);advanceHeroTurn(g);return true}
function initializeCommandEncounter(g){g.commandDeck={draw:shuffle(COMMAND_DECK_V01),discard:[],lastDraw:[],lastChoice:null};for(const e of g.enemies){e.bleedCount=0;delete e.enemyHand}}
function drawCommand(g){const deck=g.commandDeck;if(!deck.draw.length){deck.draw=shuffle(deck.discard);deck.discard=[]}return deck.draw.pop()||null}
function attachBoard(g,selections={warrior:'front',healer:'front',rogue:'front'}){g.playerBoardEnabled=true;g.commandHandMax=3;g.playerBoardAudit={events:[],consistencyChecks:0,violations:[]};g.boardSelection={...selections,rogue:'front'};if(!g.party.some(h=>h.role==='rogue'))g.party.push(rogueHero());g.telemetry.classContribution.rogue=stats();g.telemetry.actionsPlayed.rogue={};g.telemetry.cardsDrawn.rogue={};g.telemetry.handAccess.rogue={observations:0,cards:0,playable:0};g.telemetry.deaths.rogue=0;g.telemetry.miniBoss.attacks.rogue=0;g.telemetry.miniBoss.aoeDamage.rogue=0;g.telemetry.rogue={flips:0,actionsSpentOnFlip:0,stanceBlocked:{backstab:0,eviscerate:0},damage:0,firstKillContributions:0,evasionPrevented:0,preparations:0,cardsDiscarded:0};g.telemetry.priest={flips:0,actionsSpentOnFlip:0,stanceBlocked:{quick_heal:0,slow_heal:0,bandage:0},wandUses:0,wandDamage:0};g.telemetry.critical={armed:0,played:0,byHero:{warrior:0,healer:0,rogue:0},byAbility:{}};g.telemetry.revival={encounters:0,heroes:0,byHero:{warrior:0,healer:0,rogue:0}};g.telemetry.overlordCommand={deck:{attack:3,tactic:2,special:1},activations:0,cardsDrawn:0,optionsTotal:0,optionCounts:{0:0,1:0,2:0,3:0},bleedCounts:{0:0,1:0,2:0,3:0},selected:{attack:0,tactic:0,special:0},bleedLocks:0,rendApplied:0,tacticDamage:0,specialUses:0,specialDamage:0,choiceLog:[]};for(const h of g.party){const side=selections[h.role]||'front',cfg=PLAYER_BOARD_CONFIG[h.role][side],position=h.role==='rogue'?'FRONT':h.role==='healer'?'FAR':null;h.board={side,config:cfg,equipment:[h.role==='healer'?'WAND':null,null],position:{card:position,targetId:null}};h.maxHp=cfg.maxHp;h.hp=cfg.maxHp;h.deck=[...cfg.startingDeck];h.draw=shuffle(h.deck);h.discard=[];h.hand=[];h.criticalArmed=false;h.abilities=[...cfg.abilities];h.mastery=Object.fromEntries(cfg.abilities.map(a=>[a,0]));h.levels=Object.fromEntries(cfg.abilities.map(a=>[a,1]));h.invested=h.mastery;refill(h,g);boardAudit(g,'PLAYER_BOARD_SIDE_SELECTED',{hero:h.role,side,specializationName:cfg.specializationName,placeholder:!!cfg.placeholder})}applyPlayerBoardEnemyStats(g);initializeCommandEncounter(g);resetHeroTurn(g);validateBoard(g);return g}
const legacyStartEncounter=startEncounter;
startEncounter=function(g){const held=g.playerBoardEnabled?g.party.map(h=>[h,[...h.hand]]):[];legacyStartEncounter(g);if(g.playerBoardEnabled){for(const [h,hand]of held){const pool=[...h.hand,...h.draw,...h.discard];for(const card of hand)pool.splice(pool.indexOf(card),1);h.hand=hand;h.draw=shuffle(pool);h.discard=[];h.criticalArmed=false;refill(h,g)}applyPlayerBoardEnemyStats(g);initializeCommandEncounter(g);resetHeroTurn(g)}};
const legacyCheckVictory=checkVictory;
checkVictory=function(g){if(g.playerBoardEnabled&&g.state==='playing'&&!aliveEnemies(g).length){if(!aliveHeroes(g).length){g.state='lost';g.telemetry.defeatCause='party_wipe';g.currentEncounter.rounds=g.round;abandon(g);note(g,'✕ Eliminazione simultanea: nessun Eroe può rianimare il gruppo.');return}const fallen=g.party.filter(h=>h.hp<=0);if(fallen.length){g.telemetry.revival.encounters++;for(const h of fallen){h.hp=h.maxHp;h.evasion=false;h.criticalArmed=false;g.telemetry.revival.heroes++;g.telemetry.revival.byHero[h.role]++;boardAudit(g,'HERO_REVIVED',{hero:h.role,hp:h.hp})}note(g,`✚ Fine incontro: ${fallen.map(h=>NAMES[h.role]).join(', ')} torna in vita a HP massimi.`)}}return legacyCheckVictory(g)};
function setPosition(g,h,card,targetId=null){h.board.position={card,targetId};boardAudit(g,card?'POSITION_SET':'POSITION_CLEARED',{hero:h.role,card,targetId});validateBoard(g)}
function boardInvest(g,h,a){const before=h.mastery[a]||0;if(before>=5)return false;const oldLevel=boardLevel(before),value=before+1,newLevel=boardLevel(value);h.mastery[a]=value;h.levels[a]=newLevel;boardAudit(g,'ENGINE_INVESTED',{hero:h.role,ability:a,from:before,to:value});if(newLevel>oldLevel)boardAudit(g,'ABILITY_LEVEL_UP',{hero:h.role,ability:a,from:oldLevel,to:newLevel});validateBoard(g);return true}
function rogueCanPlay(h,card){const stance=h.board.position.card;return card!=='backstab'&&card!=='eviscerate'||card==='backstab'&&stance==='BEHIND'||card==='eviscerate'&&stance==='FRONT'}
function priestCanPlay(h,card){const stance=h.board.position.card;return card==='holy_pulse'||card==='slow_heal'&&stance==='FAR'||(card==='quick_heal'||card==='bandage')&&stance==='NEAR'||!['slow_heal','quick_heal','bandage'].includes(card)}
function flipRogue(g,h){if(g.state!=='playing'||h.actions<1||h.preparationPending)return false;const next=h.board.position.card==='FRONT'?'BEHIND':'FRONT';h.actions--;g.telemetry.rogue.flips++;g.telemetry.rogue.actionsSpentOnFlip++;setPosition(g,h,next);note(g,`↔ Rogue passa in ${next} (1 azione).`);return true}
function flipPriest(g,h){if(g.state!=='playing'||h.actions<1)return false;const next=h.board.position.card==='FAR'?'NEAR':'FAR';h.actions--;g.telemetry.priest.flips++;g.telemetry.priest.actionsSpentOnFlip++;setPosition(g,h,next);note(g,`↔ Priest passa in ${next} (1 azione).`);return true}
function useWand(g,h,targetValue){if(g.state!=='playing'||h.actions<1||h.board.position.card!=='FAR')return false;const target=targetOf(g,targetValue);if(!aliveEnemies(g).includes(target))return false;h.actions--;const dealt=damage(g,'healer',target,1);g.telemetry.priest.wandUses++;g.telemetry.priest.wandDamage+=dealt;note(g,`✦ Wand: ${dealt} danno a ${target.type==='miniBoss'?'Mini Boss':`Goblin ${target.id}`}.`);checkVictory(g);return true}
function rogueDraw(h,g){if(!h.draw.length){if(!h.discard.length)return;h.draw=shuffle(h.discard);h.discard=[]}const card=h.draw.pop();h.hand.push(card);g.telemetry.cardsDrawn.rogue[card]=(g.telemetry.cardsDrawn.rogue[card]||0)+1}
function criticalCanBoost(h,card){if(h.role==='rogue')return card==='backstab'||card==='eviscerate';const level=h.levels[card]||1,next=ABILITY_TEXT[card]?.[level];return h.abilities.includes(card)&&level<3&&next&&!next.startsWith('TBD')}
function toggleCritical(g,h){if(!h.hand.includes('critical')||g.state!=='playing')return false;h.criticalArmed=!h.criticalArmed;if(h.criticalArmed)g.telemetry.critical.armed++;note(g,h.criticalArmed?`✦ ${NAMES[h.role]} prepara Critico.`:`○ ${NAMES[h.role]} conserva Critico.`);return true}
function consumeCritical(g,h,card){const index=h.hand.indexOf('critical');if(index<0)return;h.hand.splice(index,1);h.discard.push('critical');h.criticalArmed=false;g.telemetry.critical.played++;g.telemetry.critical.byHero[h.role]++;g.telemetry.critical.byAbility[card]=(g.telemetry.critical.byAbility[card]||0)+1;boardAudit(g,'CRITICAL_PLAYED',{hero:h.role,ability:card})}
const legacyPlay=play;
play=function(g,h,card,targetValue){
  if(g.playerBoardEnabled&&card==='critical')return toggleCritical(g,h);
  const boosted=g.playerBoardEnabled&&h.criticalArmed&&criticalCanBoost(h,card)&&!(card==='slow_heal'&&!h.casting);
  if(g.playerBoardEnabled&&h.role==='warrior'&&card==='rend'){if(g.state!=='playing'||h.actions<=0||!h.hand.includes(card))return false;const target=targetOf(g,targetValue);if(!aliveEnemies(g).includes(target))return false;target.bleedCount=Math.min(3,(target.bleedCount||0)+1);g.telemetry.actionsPlayed.warrior.rend=(g.telemetry.actionsPlayed.warrior.rend||0)+1;g.telemetry.rend.played++;g.telemetry.rend.inserted++;g.telemetry.overlordCommand.rendApplied++;spend(h,card);note(g,`🩸 Rend v0.3: ${target.type==='miniBoss'?'Mini Boss':`Goblin ${target.id}`} sale a ${target.bleedCount} Bleed (${3-target.bleedCount} Command).`);return true}
  if(g.playerBoardEnabled&&h.role==='healer'&&!priestCanPlay(h,card)){g.telemetry.priest.stanceBlocked[card]++;note(g,`⛔ ${NAMES[card]} non è disponibile in ${h.board.position.card}.`);return false}
  if(h.role!=='rogue'||!g.playerBoardEnabled){const level=h.levels[card],sameTurnChannel=card==='slow_heal'&&h.casting?.startedEncounter===g.encounter&&h.casting.startedRound===g.round;if(boosted)h.levels[card]=level+1;if(sameTurnChannel)h.casting.startedRound--;const played=legacyPlay(g,h,card,targetValue);h.levels[card]=level;if(played&&boosted){consumeCritical(g,h,card);note(g,`✦ Critico: ${NAMES[card]} risolta temporaneamente a L${level+1}.`)}if(played&&sameTurnChannel)note(g,'✨ Cura Lenta completata con la seconda carta.');return played}
  if(g.state!=='playing'||h.actions<=0||!h.hand.includes(card)||card==='wound'||h.preparationPending)return false;if(!rogueCanPlay(h,card)){g.telemetry.rogue.stanceBlocked[card]++;note(g,`⛔ ${NAMES[card]} richiede ${card==='backstab'?'BEHIND':'FRONT'}.`);return false}const target=targetOf(g,targetValue),enemies=aliveEnemies(g);g.telemetry.actionsPlayed.rogue[card]=(g.telemetry.actionsPlayed.rogue[card]||0)+1;if(card==='backstab'||card==='eviscerate'){if(!enemies.includes(target))return false;const firstKillPending=g.currentEncounter.firstKillRound===null,power=(card==='backstab'?4:target.hp<=target.maxHp/2?3:2)+(boosted?1:0),dealt=damage(g,'rogue',target,power);g.telemetry.rogue.damage+=dealt;if(firstKillPending&&target.hp<=0)g.telemetry.rogue.firstKillContributions++;note(g,`🗡 Rogue usa ${NAMES[card]}${boosted?' + Critico':''}: ${dealt} danni.`)}else if(card==='evasion'){h.evasion=true;note(g,'💨 Evasion pronta contro il prossimo Attack single-target.')}else if(card==='preparation'){g.telemetry.rogue.preparations++;spend(h,card);rogueDraw(h,g);rogueDraw(h,g);h.preparationPending=2;note(g,'🃏 Preparation: scegli 2 Ability da scartare.');return true}spend(h,card);if(boosted)consumeCritical(g,h,card);checkVictory(g);return true
};
function discardPreparation(g,h,index){const card=h.hand[index];if(!h.preparationPending||!card||card==='wound'||card==='critical')return false;h.hand.splice(index,1);h.discard.push(card);h.preparationPending--;g.telemetry.rogue.cardsDiscarded++;if(!h.preparationPending)note(g,'✓ Preparation completata.');return true}

const legacyEnemyPhase=enemyPhase;
enemyPhase=function(g){if(!g.playerBoardEnabled)return legacyEnemyPhase(g);g.telemetry.taunt.aggroEnemiesRoundTotal+=aliveEnemies(g).filter(e=>e.taunted).length;g.telemetry.taunt.roundsObserved++;for(const e of [...aliveEnemies(g)]){let c=enemyCard(e);if(c==='bleed'||c==='bleedDamage'){if(c==='bleedDamage')damage(g,'warrior',e,1);g.telemetry.classContribution.warrior.rendCancelled++;note(g,`🩸 ${e.type==='miniBoss'?'Mini Boss':'Goblin'} ${e.id} salta l'attacco.`);continue}if(e.type==='miniBoss'&&c==='aoe'){resolveMiniBossAoe(g,e);if(!e.aoeSurge)continue;if(!aliveHeroes(g).length)break;do c=enemyCard(e);while(c==='aoe')}const targets=aliveHeroes(g);if(!targets.length)break;if(e.type==='miniBoss')g.telemetry.miniBoss.cards[c]++;const warrior=targets.find(h=>h.role==='warrior'),hadAggro=!!e.taunted,forced=hadAggro&&warrior,t=forced?warrior:targets[Math.floor(Math.random()*targets.length)],enemyDamage=e.damage||CONFIG.goblin.damage;if(c==='attack'&&t.role==='rogue'&&t.evasion){t.evasion=false;g.telemetry.rogue.evasionPrevented++;note(g,`💨 Rogue evita l'Attack di ${e.type==='miniBoss'?'Mini Boss':'Goblin'} ${e.id}.`);continue}const prevented=Math.min(t.shield,enemyDamage),hit=enemyDamage-prevented,before=t.hp;if(forced){if(g.tauntMode!=='persistent')e.taunted=false;g.telemetry.taunt.redirectedAttacks++}t.shield-=prevented;t.hp-=hit;g.telemetry.classContribution[t.role].prevention+=prevented;g.telemetry.classContribution[t.role].damageTaken+=hit;if(before>0&&t.hp<=0)g.telemetry.deaths[t.role]++;if(t.counter&&e.hp>0){damage(g,t.role,e,t.counter);t.counter=0}if(t.role==='warrior'&&t.hp<=0)g.enemies.forEach(enemy=>enemy.taunted=false);if(e.type==='miniBoss'&&c==='attack'&&e.aggroReset&&hadAggro){e.taunted=false;g.telemetry.miniBoss.aggroResets++}if(c==='dot'&&t.hp>0){t.deck.push('wound');t.draw.push('wound');note(g,`☣ Ferita top-deck su ${NAMES[t.role]}.`)}note(g,`☠ ${e.type==='miniBoss'?'Mini Boss':'Goblin'} ${e.id}: ${hit} danni a ${NAMES[t.role]}.`)}checkVictory(g);if(!aliveHeroes(g).length){g.state='lost';g.telemetry.defeatCause='party_wipe';g.currentEncounter.rounds=g.round;g.telemetry.wipeState={encounter:g.encounter+1,round:g.round,enemiesAlive:aliveEnemies(g).length};abandon(g);note(g,'✕ Party sconfitto.')}};
function chooseOverlordCard(cards){return cards.includes('dot')?'dot':cards.includes('aoe')?'aoe':cards[0]}
function resolveEnemyHandActivation(g,e){fillEnemyHand(e,g.enemyHandSize);const handBefore=[...e.enemyHand],bleeds=handBefore.filter(c=>c==='bleed').length,playable=handBefore.filter(c=>c!=='bleed'),t=g.telemetry.overlordHand;t.activations++;t.optionsTotal+=playable.length;t.optionCounts[playable.length]=(t.optionCounts[playable.length]||0)+1;t.bleedCounts[bleeds]=(t.bleedCounts[bleeds]||0)+1;if(!playable.length){e.enemyHand=[];t.bleedLocks++;t.choiceLog.push({encounter:g.encounter+1,round:g.round,enemyId:e.id,hand:handBefore,choice:null,bleedLock:true});fillEnemyHand(e,g.enemyHandSize);note(g,`🔒 BLEED LOCK: ${e.type==='miniBoss'?'Mini Boss':`Goblin ${e.id}`} salta l'attivazione e rimuove tutti i Bleed.`);return}const c=chooseOverlordCard(playable),index=e.enemyHand.indexOf(c);e.enemyHand.splice(index,1);e.discard.push(c);t.selected[c]=(t.selected[c]||0)+1;t.choiceLog.push({encounter:g.encounter+1,round:g.round,enemyId:e.id,hand:handBefore,choice:c,options:playable.length});const targets=aliveHeroes(g),warrior=targets.find(h=>h.role==='warrior'),hadAggro=!!e.taunted,target=hadAggro&&warrior?warrior:targets[Math.floor(Math.random()*targets.length)];if(c==='aoe'){resolveMiniBossAoe(g,e);fillEnemyHand(e,g.enemyHandSize);return}if(c==='attack'&&target.role==='rogue'&&target.evasion){target.evasion=false;g.telemetry.rogue.evasionPrevented++;note(g,`💨 Rogue evita l'Attack di ${e.type==='miniBoss'?'Mini Boss':'Goblin'} ${e.id}.`);fillEnemyHand(e,g.enemyHandSize);return}const enemyDamage=e.damage||CONFIG.goblin.damage,prevented=Math.min(target.shield,enemyDamage),hit=enemyDamage-prevented,before=target.hp;target.shield-=prevented;target.hp-=hit;g.telemetry.classContribution[target.role].prevention+=prevented;g.telemetry.classContribution[target.role].damageTaken+=hit;if(before>0&&target.hp<=0)g.telemetry.deaths[target.role]++;if(target.counter&&e.hp>0){damage(g,target.role,e,target.counter);target.counter=0}if(target.role==='warrior'&&target.hp<=0)g.enemies.forEach(enemy=>enemy.taunted=false);if(e.type==='miniBoss'&&c==='attack'&&e.aggroReset&&hadAggro){e.taunted=false;g.telemetry.miniBoss.aggroResets++}if(c==='dot'&&target.hp>0){target.deck.push('wound');target.draw.push('wound');note(g,`☣ DOT: Ferita top-deck su ${NAMES[target.role]}.`)}note(g,`☠ ${e.type==='miniBoss'?'Mini Boss':'Goblin'} ${e.id} sceglie ${c.toUpperCase()}: ${hit} danni a ${NAMES[target.role]}.`);fillEnemyHand(e,g.enemyHandSize)}
enemyPhase=function(g){if(!g.playerBoardEnabled)return legacyEnemyPhase(g);g.telemetry.taunt.aggroEnemiesRoundTotal+=aliveEnemies(g).filter(e=>e.taunted).length;g.telemetry.taunt.roundsObserved++;for(const e of [...aliveEnemies(g)]){if(!aliveHeroes(g).length)break;resolveEnemyHandActivation(g,e)}checkVictory(g);if(!aliveHeroes(g).length){g.state='lost';g.telemetry.defeatCause='party_wipe';g.currentEncounter.rounds=g.round;g.telemetry.wipeState={encounter:g.encounter+1,round:g.round,enemiesAlive:aliveEnemies(g).length};abandon(g);note(g,'✕ Party sconfitto.')}};
function chooseCommand(cards){return cards.includes('tactic')?'tactic':cards.includes('special')?'special':cards[0]}
function resolveTacticDamage(g,target){const power=2,prevented=Math.min(target.shield,power),hit=power-prevented,before=target.hp;target.shield-=prevented;target.hp-=hit;g.telemetry.classContribution[target.role].prevention+=prevented;g.telemetry.classContribution[target.role].damageTaken+=hit;g.telemetry.overlordCommand.tacticDamage+=hit;if(before>0&&target.hp<=0)g.telemetry.deaths[target.role]++;return hit}
function resolveCommandSpecial(g){g.telemetry.overlordCommand.specialUses++;for(const target of aliveHeroes(g)){const before=target.hp;target.hp-=3;g.telemetry.classContribution[target.role].damageTaken+=3;g.telemetry.overlordCommand.specialDamage+=3;if(before>0&&target.hp<=0)g.telemetry.deaths[target.role]++}if(!g.party.find(h=>h.role==='warrior')?.hp)g.enemies.forEach(enemy=>enemy.taunted=false);note(g,'💥 SPECIAL: 3 danni AOE a tutti gli Eroi.')}
function resolveCommandActivation(g,e){const bleed=Math.min(3,e.bleedCount||0),count=3-bleed,t=g.telemetry.overlordCommand;t.activations++;t.bleedCounts[bleed]=(t.bleedCounts[bleed]||0)+1;t.optionCounts[count]=(t.optionCounts[count]||0)+1;t.optionsTotal+=count;if(!count){e.bleedCount=0;g.commandDeck.lastDraw=[];g.commandDeck.lastChoice=null;t.bleedLocks++;t.choiceLog.push({encounter:g.encounter+1,round:g.round,enemyId:e.id,bleed:3,draw:[],choice:null,bleedLock:true});note(g,`🔒 BLEED LOCK: ${e.type==='miniBoss'?'Mini Boss':`Goblin ${e.id}`} salta l’attivazione e azzera i Bleed.`);return}const cards=Array.from({length:count},()=>drawCommand(g)).filter(Boolean),choice=chooseCommand(cards);g.commandDeck.discard.push(...cards);g.commandDeck.lastDraw=cards;g.commandDeck.lastChoice=choice;t.cardsDrawn+=cards.length;t.selected[choice]=(t.selected[choice]||0)+1;t.choiceLog.push({encounter:g.encounter+1,round:g.round,enemyId:e.id,bleed,draw:[...cards],choice});const targets=aliveHeroes(g),warrior=targets.find(h=>h.role==='warrior'),hadAggro=!!e.taunted,target=hadAggro&&warrior?warrior:targets[Math.floor(Math.random()*targets.length)];if(choice==='attack'&&target.role==='rogue'&&target.evasion){target.evasion=false;g.telemetry.rogue.evasionPrevented++;note(g,`💨 Rogue evita ATTACK di ${e.type==='miniBoss'?'Mini Boss':'Goblin'} ${e.id}.`);return}if(choice==='attack'){const power=e.damage||CONFIG.goblin.damage,prevented=Math.min(target.shield,power),hit=power-prevented,before=target.hp;target.shield-=prevented;target.hp-=hit;g.telemetry.classContribution[target.role].prevention+=prevented;g.telemetry.classContribution[target.role].damageTaken+=hit;if(before>0&&target.hp<=0)g.telemetry.deaths[target.role]++;if(target.counter&&e.hp>0){damage(g,target.role,e,target.counter);target.counter=0}note(g,`☠ ${e.type==='miniBoss'?'Mini Boss':'Goblin'} ${e.id}: ATTACK, ${hit} danni a ${NAMES[target.role]}.`)}else if(choice==='tactic'){const hit=resolveTacticDamage(g,target);if(target.hp>0){target.deck.push('wound');target.draw.push('wound')}note(g,`☣ ${e.type==='miniBoss'?'Mini Boss':'Goblin'} ${e.id}: TACTIC, ${hit} danni + Wound su ${NAMES[target.role]}.`)}else resolveCommandSpecial(g);if(target.role==='warrior'&&target.hp<=0)g.enemies.forEach(enemy=>enemy.taunted=false);if(e.type==='miniBoss'&&choice==='attack'&&e.aggroReset&&hadAggro){e.taunted=false;g.telemetry.miniBoss.aggroResets++}}
enemyPhase=function(g){if(!g.playerBoardEnabled)return legacyEnemyPhase(g);g.telemetry.taunt.aggroEnemiesRoundTotal+=aliveEnemies(g).filter(e=>e.taunted).length;g.telemetry.taunt.roundsObserved++;for(const e of [...aliveEnemies(g)]){if(!aliveHeroes(g).length)break;resolveCommandActivation(g,e)}checkVictory(g);if(!aliveHeroes(g).length){g.state='lost';g.telemetry.defeatCause='party_wipe';g.currentEncounter.rounds=g.round;g.telemetry.wipeState={encounter:g.encounter+1,round:g.round,enemiesAlive:aliveEnemies(g).length};abandon(g);note(g,'✕ Party sconfitto.')}};
const legacyEndRound=endRound;
endRound=function(g,agents=false){
  if(!g.playerBoardEnabled)return legacyEndRound(g,agents);
  if(g.state!=='playing')return;const encounter=g.encounter,rogue=g.party.find(h=>h.role==='rogue'),priest=g.party.find(h=>h.role==='healer');
  if(rogue){if(rogue.hand.includes('backstab')&&!rogueCanPlay(rogue,'backstab'))g.telemetry.rogue.stanceBlocked.backstab++;if(rogue.hand.includes('eviscerate')&&!rogueCanPlay(rogue,'eviscerate'))g.telemetry.rogue.stanceBlocked.eviscerate++}if(priest)for(const card of ['quick_heal','slow_heal','bandage'])if(priest.hand.includes(card)&&!priestCanPlay(priest,card))g.telemetry.priest.stanceBlocked[card]++;
  if(agents)for(const h of aliveHeroes(g)){agentTurn(g,h);if(g.encounter!==encounter||g.state!=='playing')return}enemyPhase(g);if(g.state!=='playing'||g.encounter!==encounter)return;g.round++;if(g.tauntMode==='round')g.enemies.forEach(e=>{if(e.tauntExpiresRound<=g.round){e.taunted=false;e.tauntExpiresRound=null}});g.party.forEach(h=>{h.actions=CONFIG.actionsPerRound;h.shield=0;h.counter=0;refill(h,g)});resetHeroTurn(g);note(g,`▶ Round ${g.round}: turno ${NAMES[g.activeRole]}.`)
};

const legacyExplorationRoomCleared=explorationRoomCleared;
explorationRoomCleared=function(g){const x=g.exploration,s=x?.specialTiles?.miniBoss;if(g.playerBoardEnabled&&x&&s&&!s.placed&&x.roomsExplored>=x.config.maxRoomsExplored-1){if(!s.unlocked){s.unlocked=true;s.available=true;s.unlockDepth=x.roomsExplored;x.threatTelemetry.miniBossUnlockDepth=x.roomsExplored;explorationEvent(x,'MINI_BOSS_UNLOCKED',{depth:x.roomsExplored,enrage:x.dungeonEnrage,guaranteedFinalRoom:true})}}return legacyExplorationRoomCleared(g)};

const legacyNewGame=newGame;
newGame=function(...args){const g=legacyNewGame(...args);return window.PLAYER_BOARD_SETUP?.enabled?attachBoard(g,window.PLAYER_BOARD_SETUP.sides):g};
const legacyClaimReward=claimReward;
claimReward=function(g,index,choice){if(!g.playerBoardEnabled)return legacyClaimReward(g,index,choice);const reward=g.pendingRewards[index];if(!reward)return;const h=reward.hero,a=reward.ability;if(choice==='deck'||(h.mastery[a]||0)>=5)addDeckCard(h,a);else boardInvest(g,h,a);g.pendingRewards.splice(index,1);if(!g.pendingRewards.length){g.state='playing';startEncounter(g)}};

function abilityTrack(h,a){const value=h.mastery[a]||0,level=boardLevel(value),steps=Array.from({length:6},(_,i)=>`<span class="mastery-step ${i===value?'current':''} ${i===2||i===5?'threshold':''}">${i}${i===2?'<small>L2</small>':i===5?'<small>L3</small>':''}</span>`).join(''),texts=ABILITY_TEXT[a]||['TBD','TBD','TBD'];return`<article class="ability-track"><header><strong>${NAMES[a]||a}</strong><b>L${level}</b></header><div class="mastery-line">${steps}</div><ol>${texts.map((t,i)=>`<li class="${i+1===level?'active':''}">L${i+1}: ${t}</li>`).join('')}</ol></article>`}
function playerBoard(h){const cfg=h.board.config,pos=h.board.position,value=`ally:${h.role}:0`,selected=game.selectedTarget===value,active=h.role===game.activeRole,positionControl=h.role==='rogue'?`<button class="flip-position" data-flip="rogue" ${!active||h.actions<1||h.preparationPending?'disabled':''}>Flip → ${pos.card==='FRONT'?'BEHIND':'FRONT'} · 1 azione</button>`:h.role==='healer'?`<button class="flip-position" data-flip="priest" ${!active||h.actions<1?'disabled':''}>Flip → ${pos.card==='FAR'?'NEAR':'FAR'} · 1 azione</button>`:`<button class="secondary clear-position" data-role="${h.role}" ${!pos.card?'disabled':''}>Svuota</button>`,equipmentOne=h.role==='healer'?`<span>WAND · FAR</span><button class="wand-action" data-wand="healer" ${!active||h.actions<1||pos.card!=='FAR'||game.state!=='playing'?'disabled':''}>1 danno · 1 azione</button>`:`<span>${h.board.equipment[0]||'Slot vuoto'}</span>`;return`<section class="player-board ${cfg.placeholder?'placeholder':''}"><div class="board-identity"><div class="art">${cfg.artwork}</div><div><span class="role-tag">${cfg.roleTag}</span><h2>${cfg.className} — ${cfg.specializationName}</h2><div class="hp-track"><strong>HP ${Math.max(0,h.hp)}/${h.maxHp}</strong>${Array.from({length:h.maxHp},(_,i)=>`<i class="${i<h.hp?'full':''}"></i>`).join('')}</div><p>${cfg.passive||'Nessuna passiva'}</p><button class="ally-target ${selected?'selected':''}" data-target="${value}">${selected?'✓ Bersaglio alleato selezionato':'Seleziona per cure/supporto'}</button></div></div><div class="board-slots"><div><b>Equipment 1</b>${equipmentOne}</div><div class="position-${pos.card?.toLowerCase()||'empty'}"><b>Position</b><span>${pos.card||'Nessuna'}${pos.targetId?` → ${pos.targetId}`:''}</span>${positionControl}</div><div><b>Equipment 2</b><span>${h.board.equipment[1]||'Slot vuoto'}</span></div></div><div class="mastery-grid">${h.abilities.map(a=>abilityTrack(h,a)).join('')}</div></section>`}
function iconSummary(icons={}){return Object.entries(icons).filter(([,n])=>n).map(([type,n])=>`<span class="tile-icon">${type==='FIGHTER'?'⚔':'◆'} ${n}</span>`).join('')||'<span class="tile-icon">Vuoto</span>'}
function renderDungeonMap(x){const node=document.getElementById('dungeonMap'),overlord=document.getElementById('overlordPanel');if(!x){node.hidden=true;overlord.hidden=true;return}node.hidden=false;overlord.hidden=false;const rooms=x.map.rooms.map(room=>`<article class="map-tile ${room.depth===0?'start':''} ${room.id===x.map.currentRoomId?'current':''}"><div class="tile-top"><span class="tile-id">${room.tileId}</span><span class="tile-state">${room.state}</span></div>${room.depth===0?'<strong>INGRESSO</strong>':`<h3>Stanza ${room.depth}</h3><div class="tile-icons">${iconSummary(room.composition?.total)}</div><div class="tile-exits">Uscite: ${(room.exits||[]).map(e=>`${e.id} [${Object.entries(e.icons||{}).filter(([,n])=>n).map(([k,n])=>`${k} ${n}`).join(', ')||'vuota'}]`).join(' · ')||'—'}</div>${room.containsMiniBoss?'<p><strong>MINI BOSS</strong></p>':''}`}</article>`).join('');const hand=x.overlordHand.map(t=>`<div class="hand-tile"><strong>${t.id} · ${t.name||'Room Tile'}</strong><span>${iconSummary(t.contentIcons)}</span><small class="muted">Uscite ${(t.exits||[]).length} · età ${x.tileAge[t.id]||0}</small></div>`).join(''),bleedState=(game.enemies||[]).filter(e=>e.hp>0).map(e=>`<div class="enemy-hand"><strong>${e.type==='miniBoss'?'Mini Boss':`Goblin ${e.id}`}</strong><div>${Array.from({length:3},(_,i)=>`<span class="command-slot ${i<(e.bleedCount||0)?'blocked':''}">${i<(e.bleedCount||0)?'🩸':'COMMAND'}</span>`).join('')}</div><small>${3-(e.bleedCount||0)} Command alla prossima attivazione</small></div>`).join(''),deck=game.commandDeck||{draw:[],discard:[],lastDraw:[]};node.innerHTML=`<div class="map-header"><h2>Mappa / stanza</h2><span class="mode-pill">${x.roomsExplored}/${x.config.maxRoomsExplored}</span></div><div class="map-path">${rooms}</div>`;overlord.innerHTML=`<h2>Overlord Command Deck</h2><p class="target-help">ATTACK ×3: 6 danni · TACTIC ×2: 2 danni + Wound · SPECIAL ×1: AOE 3</p><div class="command-status"><span>Draw ${deck.draw.length}</span><span>Discard ${deck.discard.length}</span></div>${deck.lastDraw.length?`<div class="enemy-hand"><strong>Ultima Command Hand</strong><div>${deck.lastDraw.map(c=>`<span class="enemy-card ${c}">${c.toUpperCase()}</span>`).join('')}</div><small>Scelta: ${deck.lastChoice?.toUpperCase()||'—'}</small></div>`:''}${bleedState}<details><summary>Room Tile disponibili</summary><div class="overlord-hand">${hand}</div></details>`}
function validTarget(g,value){if(!value)return false;return !!targetOf(g,value)&&((value.startsWith('ally:')&&aliveHeroes(g).includes(targetOf(g,value)))||(value.startsWith('enemy:')&&aliveEnemies(g).includes(targetOf(g,value))))}
function renderRoomTargets(g){if(!validTarget(g,g.selectedTarget)){const first=aliveEnemies(g)[0];g.selectedTarget=first?`enemy:x:${first.id}`:`ally:${aliveHeroes(g)[0]?.role||'warrior'}:0`}const enemies=aliveEnemies(g);document.getElementById('enemies').innerHTML=`<h2>Nemici nella stanza</h2><p class="target-help">Scegli direttamente chi bersagliare. La selezione resta attiva dopo ogni carta.</p><div class="room-targets">${enemies.map(e=>{const value=`enemy:x:${e.id}`,selected=g.selectedTarget===value;return`<button class="room-target ${selected?'selected':''}" data-target="${value}">${selected?'<span class="target-check">✓ TARGET</span>':''}<strong>${e.type==='miniBoss'?'Mini Boss':`Goblin ${e.id}`}</strong><small>${Math.max(0,e.hp)}/${e.maxHp} PV · Bleed ${e.bleedCount||0}/3 · Command ${3-(e.bleedCount||0)}${e.taunted?' · AGGRO':''}</small></button>`}).join('')||'<span class="muted">Nessun nemico vivo.</span>'}</div>`;const hidden=document.getElementById('target');hidden.value=g.selectedTarget}
function bindTargetButtons(){document.querySelectorAll('[data-target]').forEach(b=>b.onclick=()=>{game.selectedTarget=b.dataset.target;render()})}
function handButton(h,hi,c,i){const turnLocked=h.role!==game.activeRole;if(h.role==='rogue'&&h.preparationPending){const canDiscard=!turnLocked&&c!=='wound'&&c!=='critical';return`<button class="action ${c} ${canDiscard?'discard-choice':''}" data-discard="${i}" data-rogue="${hi}" ${canDiscard?'':'disabled'}>${canDiscard?'Scarta: ':''}${NAMES[c]}<small>${c==='wound'?'Wound non scartabile':c==='critical'?'Critico non è una Ability':`Scelte rimaste: ${h.preparationPending}`}</small></button>`}if(c==='critical')return`<button class="action critical ${h.criticalArmed?'armed':''}" data-critical="${hi}" ${turnLocked||game.state!=='playing'?'disabled':''}>${h.criticalArmed?'✓ ':''}Critico<small>${h.criticalArmed?'Pronto: scegli una Ability compatibile':'Seleziona · 0 azioni'}</small></button>`;const stanceLocked=h.role==='rogue'&&!rogueCanPlay(h,c)||h.role==='healer'&&!priestCanPlay(h,c),required=h.role==='rogue'?(c==='backstab'?'BEHIND':'FRONT'):c==='slow_heal'?'FAR':'NEAR',disabled=turnLocked||c==='wound'||h.actions<=0||game.state!=='playing'||stanceLocked;return`<button class="action ${c} ${stanceLocked?'stance-locked':''}" data-h="${hi}" data-i="${i}" ${disabled?'disabled':''}>${NAMES[c]} L${h.levels[c]||'—'}<small>${turnLocked?'In attesa del turno':stanceLocked?`Richiede ${required}`:DESC[c]}</small></button>`}

const renderBeforeBoard=render;
render=function(){renderBeforeBoard();renderDungeonMap(game.exploration);const setup=document.getElementById('boardSetup'),enabled=!!game.playerBoardEnabled;document.body.classList.toggle('player-board-active',enabled);if(setup)setup.dataset.active=enabled?'true':'false';if(enabled){renderRoomTargets(game);document.getElementById('raidStats').innerHTML+=`<div class="stat turn-stat">Turno<strong>${game.activeRole==='enemies'?'Nemici':NAMES[game.activeRole]||'—'}</strong></div>`}if(enabled&&game.state!=='reward'&&game.state!=='treasure'){document.getElementById('party').innerHTML=`<div class="hero-columns">${game.party.map((h,hi)=>`<section class="hero-column ${h.role===game.activeRole?'active-turn':'waiting-turn'}"><div class="hero"><h2>${h.role===game.activeRole?'<span class="turn-marker">▶ TURNO</span> ':''}Mano — ${NAMES[h.role]} <small class="muted">· ${h.actions} azioni · deck ${h.deck.length}</small></h2><div class="hand">${h.hand.map((c,i)=>handButton(h,hi,c,i)).join('')}</div></div>${playerBoard(h)}</section>`).join('')}</div>`;document.querySelectorAll('[data-h]').forEach(b=>b.onclick=()=>{const h=game.party[+b.dataset.h],card=h.hand[+b.dataset.i],played=play(game,h,card,game.selectedTarget);if(!played)note(game,'Giocata non valida per il bersaglio o il timing scelto.');else advanceHeroTurn(game);render()});document.querySelectorAll('[data-critical]').forEach(b=>b.onclick=()=>{toggleCritical(game,game.party[+b.dataset.critical]);render()});document.querySelectorAll('[data-discard]').forEach(b=>b.onclick=()=>{const h=game.party[+b.dataset.rogue];discardPreparation(game,h,+b.dataset.discard);advanceHeroTurn(game);render()});document.querySelectorAll('[data-flip]').forEach(b=>b.onclick=()=>{const h=game.party.find(x=>x.role===(b.dataset.flip==='priest'?'healer':'rogue'));(b.dataset.flip==='priest'?flipPriest:flipRogue)(game,h);advanceHeroTurn(game);render()});document.querySelectorAll('[data-wand]').forEach(b=>b.onclick=()=>{const h=game.party.find(x=>x.role==='healer');useWand(game,h,game.selectedTarget);advanceHeroTurn(game);render()});document.querySelectorAll('.clear-position').forEach(b=>b.onclick=()=>{setPosition(game,game.party.find(h=>h.role===b.dataset.role),null);render()});bindTargetButtons()}const end=document.getElementById('end');if(enabled&&end){const h=game.party.find(hero=>hero.role===game.activeRole);end.textContent=h?`Passa · ${NAMES[h.role]}`:'Turno nemici';end.disabled=game.state!=='playing'||!h||!!h.preparationPending}if(enabled){validateBoard(game);document.getElementById('telemetry').textContent=JSON.stringify({...game.telemetry,playerBoardAudit:game.playerBoardAudit},null,2)}};

function organizePages(){const main=document.querySelector('main'),title=main.querySelector('h1'),intro=title.nextElementSibling,setup=document.getElementById('boardSetup'),oldGrid=main.querySelector('.grid'),left=oldGrid.querySelector('section'),right=oldGrid.querySelector('aside'),combat=left.children[0],map=document.getElementById('dungeonMap'),bags=document.getElementById('bagMemory'),party=document.getElementById('party'),controls=left.querySelector('.card:last-child'),cards=[...right.querySelectorAll('.card')],logCard=cards.find(c=>c.querySelector('#log')),simulationCard=cards.find(c=>c.querySelector('#results')),telemetry=document.getElementById('telemetry').parentElement;const header=document.createElement('header');header.className='app-header';header.innerHTML=`<h1>Deck &amp; Engine — Party</h1><nav class="page-tabs"><button class="page-tab active" data-page="gamePage">Gioca</button><button class="page-tab" data-page="labPage">Simulazione &amp; test</button></nav>`;const gamePage=document.createElement('section');gamePage.id='gamePage';gamePage.className='app-page';const gameLayout=document.createElement('div');gameLayout.className='game-layout';const playColumn=document.createElement('div');playColumn.className='play-column';const battlefield=document.createElement('div');battlefield.className='battlefield';battlefield.append(combat,map);playColumn.append(battlefield,party);controls.classList.add('game-controls');playColumn.append(controls);const sidebar=document.createElement('aside');sidebar.className='game-sidebar';const overlord=document.createElement('section');overlord.id='overlordPanel';overlord.className='overlord-panel';sidebar.append(overlord,bags,logCard);gameLayout.append(playColumn,sidebar);gamePage.append(setup,gameLayout);const labPage=document.createElement('section');labPage.id='labPage';labPage.className='app-page';labPage.hidden=true;const labShell=document.createElement('div');labShell.className='lab-shell';labShell.append(simulationCard,telemetry);labPage.append(labShell);main.replaceChildren(header,gamePage,labPage);intro.remove();document.querySelectorAll('.page-tab').forEach(button=>button.onclick=()=>{document.querySelectorAll('.page-tab').forEach(x=>x.classList.toggle('active',x===button));gamePage.hidden=button.dataset.page!=='gamePage';labPage.hidden=button.dataset.page!=='labPage'});return setup}
const organizedSetup=organizePages();

function startBoardCampaign(){const sides={warrior:document.getElementById('warriorSide').value,healer:document.getElementById('healerSide').value};window.PLAYER_BOARD_SETUP={enabled:true,sides};document.getElementById('boardSetup').classList.add('setup-collapsed');game=startExplorationGame(EXPLORATION_CONFIG_T7_B,true);render()}
document.getElementById('startBoard').onclick=startBoardCampaign;
document.getElementById('startLegacy').onclick=()=>{window.PLAYER_BOARD_SETUP={enabled:false,sides:{}};game=newGame(true);render()};
document.getElementById('reset').onclick=()=>{game=window.PLAYER_BOARD_SETUP?.enabled?startExplorationGame(EXPLORATION_CONFIG_T7_B,true):newGame(true);render()};
document.getElementById('end').onclick=()=>{if(game.playerBoardEnabled)passHeroTurn(game);else endRound(game);render()};
document.getElementById('boardSmoke').onclick=()=>{const previous=window.PLAYER_BOARD_SETUP;window.PLAYER_BOARD_SETUP={enabled:false,sides:{}};const legacy=legacyNewGame(true),board=attachBoard(legacyNewGame(true),{warrior:'front',healer:'front'}),w=board.party[0],deckBefore=w.deck.length;boardInvest(board,w,'parry');boardInvest(board,w,'parry');const trackPass=w.mastery.parry===2&&w.levels.parry===2&&w.deck.length===deckBefore;addDeckCard(w,'parry');const deckPass=w.deck.length===deckBefore+1&&w.mastery.parry===2;w.hp=w.maxHp+1;const hpViolation=validateBoard(board).length===1;w.hp=w.maxHp;const events=board.playerBoardAudit.events.map(e=>e.type);const result={test:'Player Board feature-flag smoke',passed:!legacy.playerBoardEnabled&&trackPass&&deckPass&&hpViolation&&events.includes('ENGINE_INVESTED')&&events.includes('ABILITY_LEVEL_UP')&&events.includes('PLAYER_BOARD_SIDE_SELECTED'),baselineUnchanged:!legacy.playerBoardEnabled,trackPass,deckPass,hpViolation,audit:board.playerBoardAudit};document.getElementById('results').textContent=JSON.stringify(result,null,2);window.PLAYER_BOARD_SETUP=previous};
if(new URLSearchParams(location.search).get('legacy')==='1')render();else startBoardCampaign();
